CollimatorDesktop: ProccessingProperties Class Reference
ProccessingProperties Class Reference
#include <proccessingproperties.h>
Classes
struct StretchingValues
struct ThresholdValues
Public Member Functions
ProccessingProperties (ProccessingProperties *proccessingProperties)
ProccessingProperties ()
float scale ()
float refinateRadius ()
StretchingValues stretchingValues ()
ThresholdValues thresholdValues ()
void setScale (float scale)
void setRefinateRadius (float refinateRadius)
void setStretchingValues (StretchingValues values)
void setThresholdValues (ThresholdValues values)
Private Attributes
float m_scale
float m_refinateRadius
StretchingValues m_stretchingValues
ThresholdValues m_thresholdValues
Detailed Description
Definition at line 5 of file proccessingproperties.h.
Constructor & Destructor Documentation
ProccessingProperties() [1/2]
ProccessingProperties::ProccessingProperties (ProccessingProperties * proccessingProperties) explicit
Definition at line 4 of file proccessingproperties.cpp.
References m_refinateRadius, m_scale, m_stretchingValues, m_thresholdValues, refinateRadius(), scale(), stretchingValues(), and thresholdValues().
ProccessingProperties() [2/2]
ProccessingProperties::ProccessingProperties () explicit
Definition at line 12 of file proccessingproperties.cpp.
References ProccessingProperties::ThresholdValues::constant, m_refinateRadius, m_scale, m_stretchingValues, m_thresholdValues, ProccessingProperties::StretchingValues::max, ProccessingProperties::StretchingValues::min, and ProccessingProperties::ThresholdValues::thresholdSize.
Member Function Documentation
refinateRadius()
float ProccessingProperties::refinateRadius ()
Definition at line 48 of file proccessingproperties.cpp.
References m_refinateRadius.
Referenced by ProccessingProperties(), and setRefinateRadius().
scale()
float ProccessingProperties::scale ()
Definition at line 43 of file proccessingproperties.cpp.
References m_scale.
Referenced by ProccessingProperties(), and setScale().
setRefinateRadius()
void ProccessingProperties::setRefinateRadius (float refinateRadius)
Definition at line 28 of file proccessingproperties.cpp.
References m_refinateRadius, and refinateRadius().
setScale()
void ProccessingProperties::setScale (float scale)
Definition at line 23 of file proccessingproperties.cpp.
References m_scale, and scale().
setStretchingValues()
void ProccessingProperties::setStretchingValues (StretchingValues values)
Definition at line 33 of file proccessingproperties.cpp.
References m_stretchingValues.
setThresholdValues()
void ProccessingProperties::setThresholdValues (ThresholdValues values)
Definition at line 38 of file proccessingproperties.cpp.
References m_thresholdValues.
stretchingValues()
ProccessingProperties::StretchingValues ProccessingProperties::stretchingValues ()
Definition at line 53 of file proccessingproperties.cpp.
References m_stretchingValues.
Referenced by ProccessingProperties().
thresholdValues()
ProccessingProperties::ThresholdValues ProccessingProperties::thresholdValues ()
Definition at line 58 of file proccessingproperties.cpp.
References m_thresholdValues.
Referenced by ProccessingProperties().
Member Data Documentation
m_refinateRadius
float ProccessingProperties::m_refinateRadius private
Definition at line 34 of file proccessingproperties.h.
Referenced by ProccessingProperties(), refinateRadius(), and setRefinateRadius().
m_scale
float ProccessingProperties::m_scale private
Definition at line 33 of file proccessingproperties.h.
Referenced by ProccessingProperties(), scale(), and setScale().
m_stretchingValues
StretchingValues ProccessingProperties::m_stretchingValues private
Definition at line 35 of file proccessingproperties.h.
Referenced by ProccessingProperties(), setStretchingValues(), and stretchingValues().
m_thresholdValues
ThresholdValues ProccessingProperties::m_thresholdValues private
Definition at line 36 of file proccessingproperties.h.
Referenced by ProccessingProperties(), setThresholdValues(), and thresholdValues().
The documentation for this class was generated from the following files:
CollimatorLib/proccessingproperties.h
CollimatorLib/proccessingproperties.cpp