CollimatorDesktop: Screw Class Reference
Screw Class Reference
#include <screw.h>
Public Member Functions
Screw ()
Screw (float degrees)
virtual int id ()
virtual float degrees ()
void setId (int id)
void setDegrees (float degrees)
QPoint getScrewPosition (QPoint reference, int radius)
Private Attributes
int m_id
float m_degrees
Detailed Description
Definition at line 8 of file screw.h.
Constructor & Destructor Documentation
Screw() [1/2]
Screw::Screw ()
Definition at line 4 of file screw.cpp.
References m_id.
Screw() [2/2]
Screw::Screw (float degrees)
Definition at line 9 of file screw.cpp.
References degrees(), m_id, and setDegrees().
Member Function Documentation
degrees()
float Screw::degrees () virtual
Definition at line 28 of file screw.cpp.
References m_degrees.
Referenced by calculateScrewsDegrees(), getScrewPosition(), PaintingProperties::paintScrewsHelp(), qHash(), Screw(), and setDegrees().
getScrewPosition()
QPoint Screw::getScrewPosition (QPoint reference, int radius)
Definition at line 39 of file screw.cpp.
References degrees().
Referenced by PaintingProperties::paintScrewsHelp().
id()
int Screw::id () virtual
Definition at line 34 of file screw.cpp.
References m_id.
Referenced by operator==(), qHash(), and setId().
setDegrees()
void Screw::setDegrees (float degrees)
Definition at line 20 of file screw.cpp.
References degrees(), and m_degrees.
Referenced by ScrewsDialog::addScrew(), TelescopeDAO::get(), TelescopeDAO::getAll(), and Screw().
setId()
void Screw::setId (int id)
Definition at line 15 of file screw.cpp.
References id(), and m_id.
Referenced by TelescopeDAO::get(), and TelescopeDAO::getAll().
Member Data Documentation
m_degrees
float Screw::m_degrees private
Definition at line 23 of file screw.h.
Referenced by degrees(), and setDegrees().
m_id
int Screw::m_id private
Definition at line 22 of file screw.h.
Referenced by id(), Screw(), and setId().
The documentation for this class was generated from the following files:
CollimatorLib/model/screw.h
CollimatorLib/model/screw.cpp