CollimatorDesktop: INDIClient Class Reference
INDIClient Class Reference
#include <indiclient.h>
Signals
void deviceDetected (RemoteTelescope)
void imageReceived (QString)
Public Member Functions
INDIClient ()
~INDIClient ()
bool connectToServer (QString host, int port)
bool isConnectedToServer ()
void disconnect ()
void getImageFromTelescope (RemoteTelescope telescope)
Protected Member Functions
void newUniversalMessage (std::string) override
Protected Attributes
QHash< QString, INDI::BaseDevice * > devices
Private Member Functions
void newDevice (INDI::BaseDevice *) override
void removeDevice (INDI::BaseDevice *) override
void newProperty (INDI::Property *property) override
void removeProperty (INDI::Property *) override
void newBLOB (IBLOB *bp) override
void newSwitch (ISwitchVectorProperty *) override
void newNumber (INumberVectorProperty *) override
void newText (ITextVectorProperty *) override
void newLight (ILightVectorProperty *) override
void newMessage (INDI::BaseDevice *, int) override
void serverConnected () override
void serverDisconnected (int) override
Detailed Description
Definition at line 14 of file indiclient.h.
Constructor & Destructor Documentation
INDIClient()
INDIClient::INDIClient () inline
Definition at line 18 of file indiclient.h.
~INDIClient()
INDIClient::~INDIClient () inline
Definition at line 19 of file indiclient.h.
Member Function Documentation
connectToServer()
bool INDIClient::connectToServer (QString host, int port)
Definition at line 5 of file indiclient.cpp.
Referenced by CollimatorImage::connectTelescope(), and ConnectionSettingsDialog::connectToServer().
deviceDetected
void INDIClient::deviceDetected (RemoteTelescope) signal
Referenced by ConnectionSettingsDialog::ConnectionSettingsDialog(), and CollimatorImage::connectTelescope().
disconnect()
void INDIClient::disconnect ()
Definition at line 20 of file indiclient.cpp.
Referenced by ConnectionSettingsDialog::connectToServer(), CollimatorImage::setConnected(), and CollimatorImage::~CollimatorImage().
getImageFromTelescope()
void INDIClient::getImageFromTelescope (RemoteTelescope telescope)
Definition at line 25 of file indiclient.cpp.
References devices, RemoteTelescope::exposure(), and RemoteTelescope::name().
Referenced by CollimatorImage::imageReceived(), and CollimatorImage::telescopeDetected().
imageReceived
void INDIClient::imageReceived (QString) signal
Referenced by CollimatorImage::telescopeDetected().
isConnectedToServer()
bool INDIClient::isConnectedToServer ()
Definition at line 15 of file indiclient.cpp.
Referenced by CollimatorImage::~CollimatorImage().
newBLOB()
void INDIClient::newBLOB (IBLOB * bp) inline override private
Definition at line 42 of file indiclient.h.
newDevice()
void INDIClient::newDevice (INDI::BaseDevice *) inline override private
Definition at line 32 of file indiclient.h.
newLight()
void INDIClient::newLight (ILightVectorProperty *) inline override private
Definition at line 53 of file indiclient.h.
newMessage()
void INDIClient::newMessage (INDI::BaseDevice * , int) inline override private
Definition at line 54 of file indiclient.h.
newNumber()
void INDIClient::newNumber (INumberVectorProperty *) inline override private
Definition at line 51 of file indiclient.h.
newProperty()
void INDIClient::newProperty (INDI::Property * property) inline override private
Definition at line 34 of file indiclient.h.
newSwitch()
void INDIClient::newSwitch (ISwitchVectorProperty *) inline override private
Definition at line 50 of file indiclient.h.
newText()
void INDIClient::newText (ITextVectorProperty *) inline override private
Definition at line 52 of file indiclient.h.
newUniversalMessage()
void INDIClient::newUniversalMessage (std::string) inline override protected
Definition at line 59 of file indiclient.h.
removeDevice()
void INDIClient::removeDevice (INDI::BaseDevice *) inline override private
Definition at line 33 of file indiclient.h.
removeProperty()
void INDIClient::removeProperty (INDI::Property *) inline override private
Definition at line 41 of file indiclient.h.
serverConnected()
void INDIClient::serverConnected () inline override private
Definition at line 55 of file indiclient.h.
serverDisconnected()
void INDIClient::serverDisconnected (int) inline override private
Definition at line 56 of file indiclient.h.
Member Data Documentation
devices
QHash<QString, INDI::BaseDevice*> INDIClient::devices protected
Definition at line 61 of file indiclient.h.
Referenced by getImageFromTelescope().
The documentation for this class was generated from the following files:
CollimatorLib/model/indiclient.h
CollimatorLib/model/indiclient.cpp