CollimatorDesktop: PaintingPropertiesDAO Class Reference
PaintingPropertiesDAO Class Reference
#include <paintingpropertiesdao.h>
Public Member Functions
int save (PaintingProperties *paintingProperties)
save Method for saving an instance of PaintingProperties
int update (PaintingProperties paintingProperties)
update Method for updating an instance of PaintingProperties
PaintingProperties get (int id)
get Mehod for obtaining a PaintingProperties by its id
QList< PaintingProperties > getAll ()
getAll Mehod for obtaining all PaintingProperties in the database
bool remove (int id)
remove Method for removing a PaintingProperties by its id
Static Public Member Functions
static PaintingProperties createObject (QSqlQuery query)
createObject Method for getting PaintingProperties object given a query
Private Member Functions
void bindValues (QSqlQuery *query, PaintingProperties paintingProperties)
bindValues Private method for binding values fo the query with PaintingProperties to reduce code
Private Attributes
DatabaseConnectionSingleton db = DatabaseConnectionSingleton::instance()
Detailed Description
Definition at line 8 of file paintingpropertiesdao.h.
Member Function Documentation
bindValues()
void PaintingPropertiesDAO::bindValues (QSqlQuery * query, PaintingProperties paintingProperties) private
bindValues Private method for binding values fo the query with PaintingProperties to reduce code
Parameters
query Query where to replace data
paintingProperties PaintingProperties from where to get data
Definition at line 85 of file paintingpropertiesdao.cpp.
References PaintingProperties::automatic(), PaintingProperties::Scope::center, PaintingProperties::Mirroring::horizontally, PaintingProperties::imageMirroring(), PaintingProperties::Scope::radius, PaintingProperties::scope(), PaintingProperties::screwsMirroring(), PaintingProperties::screwsRadius(), PaintingProperties::tightMirroring(), PaintingProperties::Mirroring::vertically, PaintingProperties::viewBoundingBox(), PaintingProperties::viewCalculatedCenter(), PaintingProperties::viewScrews(), and PaintingProperties::zoom().
Referenced by save(), and update().
createObject()
PaintingProperties PaintingPropertiesDAO::createObject (QSqlQuery query) static
createObject Method for getting PaintingProperties object given a query
Parameters
query Query containing values
Returns
PaintingProperties given the data from the current row of the query
Definition at line 104 of file paintingpropertiesdao.cpp.
References PaintingProperties::Scope::center, PaintingProperties::Mirroring::horizontally, PaintingProperties::Scope::radius, PaintingProperties::setAutomatic(), PaintingProperties::setId(), PaintingProperties::setImageMirroring(), PaintingProperties::setScope(), PaintingProperties::setScrewsMirroring(), PaintingProperties::setScrewsRadius(), PaintingProperties::setTigthMirroring(), PaintingProperties::setViewBoundingBox(), PaintingProperties::setViewCalculatedCenter(), PaintingProperties::setViewScrews(), PaintingProperties::setZoom(), and PaintingProperties::Mirroring::vertically.
Referenced by get(), and getAll().
get()
PaintingProperties PaintingPropertiesDAO::get (int id)
get Mehod for obtaining a PaintingProperties by its id
Parameters
id Id of the telescope to be obtained
Returns
Definition at line 58 of file paintingpropertiesdao.cpp.
References createObject(), db, and DatabaseConnectionSingleton::getDatabase().
Referenced by TelescopeDAO::get().
getAll()
QList< PaintingProperties > PaintingPropertiesDAO::getAll ()
getAll Mehod for obtaining all PaintingProperties in the database
Returns
QList<PaintingProperites> List of all PaintingProperties
Definition at line 71 of file paintingpropertiesdao.cpp.
References createObject(), db, and DatabaseConnectionSingleton::getDatabase().
remove()
bool PaintingPropertiesDAO::remove (int id)
remove Method for removing a PaintingProperties by its id
Parameters
id Id of the PaintingProperties to be removed
Returns
bool indicating if removing was successful
save()
int PaintingPropertiesDAO::save (PaintingProperties * paintingProperties)
save Method for saving an instance of PaintingProperties
Parameters
paintingProperties PaintingProperties to be saved
Returns
id of the saved PaintingProperties
Definition at line 3 of file paintingpropertiesdao.cpp.
References bindValues(), db, DatabaseConnectionSingleton::getDatabase(), and PaintingProperties::id().
Referenced by TelescopeDAO::save().
update()
int PaintingPropertiesDAO::update (PaintingProperties paintingProperties)
update Method for updating an instance of PaintingProperties
Parameters
paintingProperties to be opdated
Returns
id of the painting properties
Definition at line 28 of file paintingpropertiesdao.cpp.
References bindValues(), db, DatabaseConnectionSingleton::getDatabase(), and PaintingProperties::id().
Referenced by TelescopeDAO::update().
Member Data Documentation
db
DatabaseConnectionSingleton PaintingPropertiesDAO::db = DatabaseConnectionSingleton::instance() private
Definition at line 58 of file paintingpropertiesdao.h.
Referenced by get(), getAll(), save(), and update().
The documentation for this class was generated from the following files:
persistence/paintingpropertiesdao.h
persistence/paintingpropertiesdao.cpp