CollimatorDesktop: ConnectionSettingsDialog Class Reference
ConnectionSettingsDialog Class Reference
#include <connectionsettingsdialog.h>
Public Member Functions
ConnectionSettingsDialog (QWidget *parent=nullptr)
~ConnectionSettingsDialog ()
void setRemoteTelescope (RemoteTelescope remoteTelescope)
setRemoteTelescope Sets the remote telescope from where to show the data
RemoteTelescope remoteTelescope ()
remoteTelescope Returns the current Remote Telescope with values from UI input
Private Slots
void connectToServer ()
void deviceDetected (RemoteTelescope)
void ok ()
Private Attributes
Ui::ConnectionSettingsDialog * ui
INDIClient indiClient
RemoteTelescope m_remoteTelescope
Detailed Description
Definition at line 12 of file connectionsettingsdialog.h.
Constructor & Destructor Documentation
ConnectionSettingsDialog()
ConnectionSettingsDialog::ConnectionSettingsDialog (QWidget * parent = nullptr) explicit
Definition at line 9 of file connectionsettingsdialog.cpp.
References connectToServer(), INDIClient::deviceDetected(), deviceDetected(), indiClient, ok(), and ui.
~ConnectionSettingsDialog()
ConnectionSettingsDialog::~ConnectionSettingsDialog ()
Definition at line 24 of file connectionsettingsdialog.cpp.
References ui.
Member Function Documentation
connectToServer
void ConnectionSettingsDialog::connectToServer () private slot
Definition at line 42 of file connectionsettingsdialog.cpp.
References INDIClient::connectToServer(), INDIClient::disconnect(), indiClient, and ui.
Referenced by ConnectionSettingsDialog().
deviceDetected
void ConnectionSettingsDialog::deviceDetected (RemoteTelescope remoteTelescope) private slot
Definition at line 30 of file connectionsettingsdialog.cpp.
References RemoteTelescope::name(), remoteTelescope(), and ui.
Referenced by ConnectionSettingsDialog().
ok
void ConnectionSettingsDialog::ok () private slot
Definition at line 69 of file connectionsettingsdialog.cpp.
References m_remoteTelescope, RemoteTelescope::setExposure(), RemoteTelescope::setHost(), RemoteTelescope::setName(), RemoteTelescope::setPort(), and ui.
Referenced by ConnectionSettingsDialog().
remoteTelescope()
RemoteTelescope ConnectionSettingsDialog::remoteTelescope ()
remoteTelescope Returns the current Remote Telescope with values from UI input
Returns
Remote Telescope with values from UI input
Definition at line 89 of file connectionsettingsdialog.cpp.
References m_remoteTelescope.
Referenced by TelescopeView::connectionSettings(), deviceDetected(), and setRemoteTelescope().
setRemoteTelescope()
void ConnectionSettingsDialog::setRemoteTelescope (RemoteTelescope remoteTelescope)
setRemoteTelescope Sets the remote telescope from where to show the data
Parameters
remoteTelescope Remote telescope with data
Definition at line 95 of file connectionsettingsdialog.cpp.
References RemoteTelescope::exposure(), RemoteTelescope::host(), m_remoteTelescope, RemoteTelescope::name(), RemoteTelescope::port(), remoteTelescope(), and ui.
Referenced by TelescopeView::connectionSettings().
Member Data Documentation
indiClient
INDIClient ConnectionSettingsDialog::indiClient private
Definition at line 35 of file connectionsettingsdialog.h.
Referenced by ConnectionSettingsDialog(), and connectToServer().
m_remoteTelescope
RemoteTelescope ConnectionSettingsDialog::m_remoteTelescope private
Definition at line 36 of file connectionsettingsdialog.h.
Referenced by ok(), remoteTelescope(), and setRemoteTelescope().
ui
Ui::ConnectionSettingsDialog* ConnectionSettingsDialog::ui private
Definition at line 34 of file connectionsettingsdialog.h.
Referenced by ConnectionSettingsDialog(), connectToServer(), deviceDetected(), ok(), setRemoteTelescope(), and ~ConnectionSettingsDialog().
The documentation for this class was generated from the following files:
views/connectionsettingsdialog.h
views/connectionsettingsdialog.cpp