CollimatorDesktop: ImageResults Class Reference
ImageResults Class Reference
#include <imageresults.h>
Classes
struct Point
struct Rect
Public Member Functions
ImageResults (Point center, Rect boundingBox, ProcessingProperties processingProperties)
Point center ()
ProcessingProperties processingProperties ()
Rect boundingBox ()
CollimationAction getAction (Telescope telescope)
Private Attributes
Point m_center
ProcessingProperties m_properties
Rect m_boundingBox
Detailed Description
Definition at line 9 of file imageresults.h.
Constructor & Destructor Documentation
ImageResults()
ImageResults::ImageResults (Point center, Rect boundingBox, ProcessingProperties processingProperties) explicit
Definition at line 8 of file imageresults.cpp.
References boundingBox(), center(), m_boundingBox, m_center, m_properties, and processingProperties().
Member Function Documentation
boundingBox()
ImageResults::Rect ImageResults::boundingBox ()
Definition at line 20 of file imageresults.cpp.
References m_boundingBox.
Referenced by ImageResults(), and PaintingProperties::paint().
center()
ImageResults::Point ImageResults::center ()
Definition at line 25 of file imageresults.cpp.
References m_center.
Referenced by ImageResults(), and PaintingProperties::paint().
getAction()
CollimationAction ImageResults::getAction (Telescope telescope)
Definition at line 30 of file imageresults.cpp.
References ImageResults::Rect::heigth, CollimationAction::Loosen, m_boundingBox, m_center, Telescope::screws(), CollimationAction::Tighten, ImageResults::Rect::width, ImageResults::Point::x, ImageResults::Rect::x, ImageResults::Point::y, and ImageResults::Rect::y.
Referenced by PaintingProperties::paintScrewsHelp().
processingProperties()
ProcessingProperties ImageResults::processingProperties ()
Definition at line 15 of file imageresults.cpp.
References m_properties.
Referenced by ImageResults().
Member Data Documentation
m_boundingBox
Rect ImageResults::m_boundingBox private
Definition at line 29 of file imageresults.h.
Referenced by boundingBox(), getAction(), and ImageResults().
m_center
Point ImageResults::m_center private
Definition at line 27 of file imageresults.h.
Referenced by center(), getAction(), and ImageResults().
m_properties
ProcessingProperties ImageResults::m_properties private
Definition at line 28 of file imageresults.h.
Referenced by ImageResults(), and processingProperties().
The documentation for this class was generated from the following files:
CollimatorLib/imageresults.h
CollimatorLib/imageresults.cpp