CollimatorDesktop: Collimator Class Reference
Collimator Class Reference
#include <collimator.h>
Public Member Functions
Collimator (ProcessingProperties *propiertes)
ImageResults * proccessImage (QImage image, bool showdebug=false)
Static Public Member Functions
static Mat loadFitsImage (char *filename)
Public Attributes
Mat original
Mat scaled
Mat binary
Static Private Member Functions
static void strench (Mat *img, int vmin, int vmax)
strench Contrast stretching
static void massCenter (Mat *img, float *cx, float *cy)
massCenter Calcula el centro de masa a partir de la escala de grises; cuando es blanco, suma el valor para mas tarde dividirlo
static Rect boundingBox (Mat *img, int cx, int cy, int radius)
Private Attributes
ProcessingProperties * m_propiertes
Detailed Description
Definition at line 13 of file collimator.h.
Constructor & Destructor Documentation
Collimator()
Collimator::Collimator (ProcessingProperties * propiertes)
Definition at line 16 of file collimator.cpp.
References m_propiertes.
Member Function Documentation
boundingBox()
Rect Collimator::boundingBox (Mat * img, int cx, int cy, int radius) static private
Definition at line 133 of file collimator.cpp.
Referenced by proccessImage().
loadFitsImage()
Mat Collimator::loadFitsImage (char * filename) static
Definition at line 21 of file collimator.cpp.
Referenced by CollimatorImage::loadImage().
massCenter()
void Collimator::massCenter (Mat * img, float * cx, float * cy) static private
massCenter Calcula el centro de masa a partir de la escala de grises; cuando es blanco, suma el valor para mas tarde dividirlo
Parameters
img
cx
cy
radius radio desde x e y, si es 0 es TODA la imagen
Definition at line 99 of file collimator.cpp.
Referenced by proccessImage().
proccessImage()
ImageResults * Collimator::proccessImage (QImage image, bool showdebug = false)
Definition at line 172 of file collimator.cpp.
References binary, boundingBox(), ProcessingProperties::ThresholdValues::constant, m_propiertes, massCenter(), ProcessingProperties::StretchingValues::max, ProcessingProperties::StretchingValues::min, original, ProcessingProperties::refinateRadius(), ProcessingProperties::scale(), scaled, strench(), ProcessingProperties::stretchingValues(), ProcessingProperties::ThresholdValues::thresholdSize, ProcessingProperties::thresholdValues(), ImageResults::Point::x, and ImageResults::Point::y.
Referenced by CollimatorImage::refreshImage().
strench()
void Collimator::strench (Mat * img, int vmin, int vmax) static private
strench Contrast stretching
Parameters
img imagen
vmin
vmax
Definition at line 72 of file collimator.cpp.
Referenced by proccessImage().
Member Data Documentation
binary
Mat Collimator::binary
Definition at line 20 of file collimator.h.
Referenced by proccessImage().
m_propiertes
ProcessingProperties* Collimator::m_propiertes private
Definition at line 25 of file collimator.h.
Referenced by Collimator(), and proccessImage().
original
Mat Collimator::original
Definition at line 18 of file collimator.h.
Referenced by proccessImage().
scaled
Mat Collimator::scaled
Definition at line 19 of file collimator.h.
Referenced by proccessImage().
The documentation for this class was generated from the following files:
CollimatorLib/collimator.h
CollimatorLib/collimator.cpp