CollimatorDesktop: TelescopeUI Class Reference
TelescopeUI Class Reference
The TelescopeUI class Child of Telescope for implementing PaintingProperties into telescope, necessary for drawing in UI.
#include <telescopeui.h>
Public Member Functions
TelescopeUI (TelescopeUI *)
TelescopeUI ()
PaintingProperties * paintingProperties ()
void setPaintingProperties (PaintingProperties paintingProperties)
setPaintingProperties Sets the given PaintingProperties to the telescope
Public Member Functions inherited from Telescope
Telescope (Telescope *telescope)
Telescope ()
int id ()
QString name ()
ProcessingProperties processingProperties ()
RemoteTelescope remoteTelescope ()
QList< Screw > screws ()
void setId (int id)
void setName (QString name)
void setProcessingProperties (ProcessingProperties processingproperties)
void setScrews (QList< Screw > screws)
void setRemoteTelescope (RemoteTelescope remoteTelescope)
Private Attributes
PaintingProperties * m_paintingProperties
Detailed Description
The TelescopeUI class Child of Telescope for implementing PaintingProperties into telescope, necessary for drawing in UI.
Definition at line 11 of file telescopeui.h.
Constructor & Destructor Documentation
TelescopeUI() [1/2]
TelescopeUI::TelescopeUI (TelescopeUI * telescope)
Definition at line 3 of file telescopeui.cpp.
References m_paintingProperties, and paintingProperties().
TelescopeUI() [2/2]
TelescopeUI::TelescopeUI ()
Definition at line 8 of file telescopeui.cpp.
References m_paintingProperties.
Member Function Documentation
paintingProperties()
PaintingProperties * TelescopeUI::paintingProperties ()
Returns
Pointer to the processing properties of the telescope
Definition at line 18 of file telescopeui.cpp.
References m_paintingProperties.
Referenced by TelescopeView::changeProperties(), CollimatorImage::mousePressEvent(), CollimatorImage::mouseReleaseEvent(), CollimatorImage::refreshImage(), TelescopeDAO::save(), TelescopeView::screwsSettings(), TelescopeView::setAutomatic(), setPaintingProperties(), TelescopeView::setTelescope(), TelescopeUI(), TelescopeDAO::update(), and CollimatorImage::zoom().
setPaintingProperties()
void TelescopeUI::setPaintingProperties (PaintingProperties paintingProperties)
setPaintingProperties Sets the given PaintingProperties to the telescope
Parameters
paintingProperties
Definition at line 13 of file telescopeui.cpp.
References m_paintingProperties, and paintingProperties().
Referenced by TelescopeDAO::createObject(), TelescopeDAO::get(), and TelescopeDAO::save().
Member Data Documentation
m_paintingProperties
PaintingProperties* TelescopeUI::m_paintingProperties private
Definition at line 29 of file telescopeui.h.
Referenced by paintingProperties(), setPaintingProperties(), and TelescopeUI().
The documentation for this class was generated from the following files:
logic/telescopeui.h
logic/telescopeui.cpp