CollimatorDesktop: TelescopeSelector Class Reference
TelescopeSelector Class Reference
#include <telescopeselector.h>
Public Member Functions
TelescopeSelector (QWidget *parent=nullptr)
~TelescopeSelector ()
Protected Member Functions
bool eventFilter (QObject *object, QEvent *event)
Private Slots
void onClickTelescope ()
void createTelescope ()
void removeTelescope ()
Private Member Functions
void paintTelescopeList (QList< TelescopeUI > telescopes)
Private Attributes
Ui::TelescopeSelector * ui
QList< TelescopeUI > m_telescopes
bool creating = false
Detailed Description
Definition at line 14 of file telescopeselector.h.
Constructor & Destructor Documentation
TelescopeSelector()
TelescopeSelector::TelescopeSelector (QWidget * parent = nullptr)
Definition at line 13 of file telescopeselector.cpp.
References createTelescope(), TelescopeDAO::getAll(), onClickTelescope(), paintTelescopeList(), removeTelescope(), and ui.
~TelescopeSelector()
TelescopeSelector::~TelescopeSelector ()
Definition at line 31 of file telescopeselector.cpp.
References ui.
Member Function Documentation
createTelescope
void TelescopeSelector::createTelescope () private slot
Definition at line 61 of file telescopeselector.cpp.
References creating, m_telescopes, Telescope::name(), TelescopeDAO::save(), Telescope::setName(), and ui.
Referenced by TelescopeSelector().
eventFilter()
bool TelescopeSelector::eventFilter (QObject * object, QEvent * event) protected
Definition at line 100 of file telescopeselector.cpp.
References creating, onClickTelescope(), removeTelescope(), and ui.
onClickTelescope
void TelescopeSelector::onClickTelescope () private slot
Definition at line 49 of file telescopeselector.cpp.
References m_telescopes, TelescopeView::setTelescope(), and ui.
Referenced by eventFilter(), and TelescopeSelector().
paintTelescopeList()
void TelescopeSelector::paintTelescopeList (QList< TelescopeUI > telescopes) private
Definition at line 37 of file telescopeselector.cpp.
References m_telescopes, and ui.
Referenced by TelescopeSelector().
removeTelescope
void TelescopeSelector::removeTelescope () private slot
Definition at line 86 of file telescopeselector.cpp.
References Telescope::id(), m_telescopes, TelescopeDAO::remove(), and ui.
Referenced by eventFilter(), and TelescopeSelector().
Member Data Documentation
creating
bool TelescopeSelector::creating = false private
Definition at line 25 of file telescopeselector.h.
Referenced by createTelescope(), and eventFilter().
m_telescopes
QList<TelescopeUI> TelescopeSelector::m_telescopes private
Definition at line 24 of file telescopeselector.h.
Referenced by createTelescope(), onClickTelescope(), paintTelescopeList(), and removeTelescope().
ui
Ui::TelescopeSelector* TelescopeSelector::ui private
Definition at line 23 of file telescopeselector.h.
Referenced by createTelescope(), eventFilter(), onClickTelescope(), paintTelescopeList(), removeTelescope(), TelescopeSelector(), and ~TelescopeSelector().
The documentation for this class was generated from the following files:
views/telescopeselector.h
views/telescopeselector.cpp