CollimatorDesktop: DatabaseConnectionSingleton Class Reference
DatabaseConnectionSingleton Class Reference
DatabaseConnectionSingleton Class for using only one instance of the database. SQLQLITE only accepts one connection at time.
#include <databaseconnectionsingleton.h>
Public Member Functions
QSqlDatabase getDatabase ()
getDatabase
Static Public Member Functions
static DatabaseConnectionSingleton & instance ()
instance Method that creates an instance if it is not created or returns the created instance
Private Member Functions
DatabaseConnectionSingleton ()
void createTables ()
createTables Method that creates all tables needed
Private Attributes
QSqlDatabase db
Detailed Description
DatabaseConnectionSingleton Class for using only one instance of the database. SQLQLITE only accepts one connection at time.
Definition at line 11 of file databaseconnectionsingleton.h.
Constructor & Destructor Documentation
DatabaseConnectionSingleton()
DatabaseConnectionSingleton::DatabaseConnectionSingleton () private
Definition at line 3 of file databaseconnectionsingleton.cpp.
References createTables(), and db.
Referenced by instance().
Member Function Documentation
createTables()
void DatabaseConnectionSingleton::createTables () private
createTables Method that creates all tables needed
Definition at line 30 of file databaseconnectionsingleton.cpp.
References db.
Referenced by DatabaseConnectionSingleton().
getDatabase()
QSqlDatabase DatabaseConnectionSingleton::getDatabase ()
getDatabase
Returns
Returns single instance of the database
Definition at line 87 of file databaseconnectionsingleton.cpp.
References db.
Referenced by PaintingPropertiesDAO::get(), ProcessingPropertiesDAO::get(), RemoteTelescopeDAO::get(), TelescopeDAO::get(), PaintingPropertiesDAO::getAll(), ProcessingPropertiesDAO::getAll(), RemoteTelescopeDAO::getAll(), TelescopeDAO::getAll(), ProcessingPropertiesDAO::remove(), RemoteTelescopeDAO::remove(), TelescopeDAO::remove(), PaintingPropertiesDAO::save(), ProcessingPropertiesDAO::save(), RemoteTelescopeDAO::save(), TelescopeDAO::save(), PaintingPropertiesDAO::update(), ProcessingPropertiesDAO::update(), RemoteTelescopeDAO::update(), and TelescopeDAO::update().
instance()
DatabaseConnectionSingleton & DatabaseConnectionSingleton::instance () static
instance Method that creates an instance if it is not created or returns the created instance
Returns
instance of the databse connection
Definition at line 21 of file databaseconnectionsingleton.cpp.
References DatabaseConnectionSingleton().
Member Data Documentation
db
QSqlDatabase DatabaseConnectionSingleton::db private
Definition at line 29 of file databaseconnectionsingleton.h.
Referenced by createTables(), DatabaseConnectionSingleton(), and getDatabase().
The documentation for this class was generated from the following files:
persistence/databaseconnectionsingleton.h
persistence/databaseconnectionsingleton.cpp