CollimatorDesktop: Telescope Class Reference
Telescope Class Reference
#include <telescope.h>
Public Member Functions
Telescope (Telescope *telescope)
Telescope ()
int id ()
QString name ()
ProcessingProperties processingProperties ()
RemoteTelescope remoteTelescope ()
QList< Screw > screws ()
void setId (int id)
void setName (QString name)
void setProcessingProperties (ProcessingProperties processingproperties)
void setScrews (QList< Screw > screws)
void setRemoteTelescope (RemoteTelescope remoteTelescope)
Private Attributes
int m_id
QString m_name
ProcessingProperties m_processingProperties
QList< Screw > m_screws
RemoteTelescope m_remoteTelescope
Detailed Description
Definition at line 10 of file telescope.h.
Constructor & Destructor Documentation
Telescope() [1/2]
Telescope::Telescope (Telescope * telescope) explicit
Definition at line 4 of file telescope.cpp.
References id(), m_id, m_name, m_processingProperties, m_screws, name(), processingProperties(), and screws().
Telescope() [2/2]
Telescope::Telescope () explicit
Definition at line 12 of file telescope.cpp.
References m_id, m_name, m_processingProperties, and m_screws.
Member Function Documentation
id()
int Telescope::id ()
Definition at line 56 of file telescope.cpp.
References m_id.
Referenced by TelescopeSelector::removeTelescope(), TelescopeDAO::save(), setId(), Telescope(), and TelescopeDAO::update().
name()
QString Telescope::name ()
Definition at line 61 of file telescope.cpp.
References m_name.
Referenced by TelescopeSelector::createTelescope(), TelescopeDAO::save(), setName(), TelescopeView::setTelescope(), Telescope(), and TelescopeDAO::update().
processingProperties()
ProcessingProperties Telescope::processingProperties ()
Definition at line 67 of file telescope.cpp.
References m_processingProperties.
Referenced by TelescopeView::openImageProcessing(), CollimatorImage::refreshImage(), TelescopeDAO::save(), setProcessingProperties(), Telescope(), and TelescopeDAO::update().
remoteTelescope()
RemoteTelescope Telescope::remoteTelescope ()
Definition at line 77 of file telescope.cpp.
References m_remoteTelescope.
Referenced by TelescopeView::connectionSettings(), TelescopeDAO::save(), setRemoteTelescope(), TelescopeView::setTelescope(), and TelescopeDAO::update().
screws()
QList< Screw > Telescope::screws ()
Definition at line 72 of file telescope.cpp.
References m_screws.
Referenced by ImageResults::getAction(), PaintingProperties::paint(), CollimatorImage::refreshImage(), TelescopeDAO::save(), TelescopeView::screwsSettings(), setScrews(), Telescope(), and TelescopeDAO::update().
setId()
void Telescope::setId (int id)
Definition at line 24 of file telescope.cpp.
References id(), and m_id.
Referenced by TelescopeDAO::createObject(), TelescopeDAO::get(), and TelescopeDAO::save().
setName()
void Telescope::setName (QString name)
Definition at line 29 of file telescope.cpp.
References m_name, and name().
Referenced by TelescopeDAO::createObject(), TelescopeSelector::createTelescope(), and TelescopeDAO::get().
setProcessingProperties()
void Telescope::setProcessingProperties (ProcessingProperties processingproperties)
Definition at line 36 of file telescope.cpp.
References m_processingProperties, and processingProperties().
Referenced by TelescopeDAO::createObject(), TelescopeDAO::get(), TelescopeView::openImageProcessing(), and TelescopeDAO::save().
setRemoteTelescope()
void Telescope::setRemoteTelescope (RemoteTelescope remoteTelescope)
Definition at line 82 of file telescope.cpp.
References m_remoteTelescope, and remoteTelescope().
Referenced by TelescopeDAO::createObject(), TelescopeDAO::get(), and TelescopeDAO::save().
setScrews()
void Telescope::setScrews (QList< Screw > screws)
Definition at line 41 of file telescope.cpp.
References m_screws, and screws().
Referenced by TelescopeDAO::get(), CollimatorImage::refreshImage(), and TelescopeView::screwsSettings().
Member Data Documentation
m_id
int Telescope::m_id private
Definition at line 29 of file telescope.h.
Referenced by id(), setId(), and Telescope().
m_name
QString Telescope::m_name private
Definition at line 30 of file telescope.h.
Referenced by name(), setName(), and Telescope().
m_processingProperties
ProcessingProperties Telescope::m_processingProperties private
Definition at line 31 of file telescope.h.
Referenced by processingProperties(), setProcessingProperties(), and Telescope().
m_remoteTelescope
RemoteTelescope Telescope::m_remoteTelescope private
Definition at line 33 of file telescope.h.
Referenced by remoteTelescope(), and setRemoteTelescope().
m_screws
QList<Screw> Telescope::m_screws private
Definition at line 32 of file telescope.h.
Referenced by screws(), setScrews(), and Telescope().
The documentation for this class was generated from the following files:
CollimatorLib/model/telescope.h
CollimatorLib/model/telescope.cpp