CollimatorDesktop: CollimationAction Class Reference
CollimationAction Class Reference
#include <collimationaction.h>
Public Types
enum Action { Loosen , Tighten }
Public Member Functions
CollimationAction (Action, Screw)
Action action ()
Screw screw ()
Private Attributes
Action m_action
Screw m_screw
Detailed Description
Definition at line 7 of file collimationaction.h.
Member Enumeration Documentation
Action
enum CollimationAction::Action
Enumerator
Loosen
Tighten
Definition at line 10 of file collimationaction.h.
Constructor & Destructor Documentation
CollimationAction()
CollimationAction::CollimationAction (Action action, Screw screw)
Definition at line 3 of file collimationaction.cpp.
References action(), m_action, m_screw, and screw().
Member Function Documentation
action()
CollimationAction::Action CollimationAction::action ()
Definition at line 9 of file collimationaction.cpp.
References m_action.
Referenced by CollimationAction(), and PaintingProperties::paintScrewsHelp().
screw()
Screw CollimationAction::screw ()
Definition at line 14 of file collimationaction.cpp.
References m_screw.
Referenced by CollimationAction(), and PaintingProperties::paintScrewsHelp().
Member Data Documentation
m_action
Action CollimationAction::m_action private
Definition at line 20 of file collimationaction.h.
Referenced by action(), and CollimationAction().
m_screw
Screw CollimationAction::m_screw private
Definition at line 21 of file collimationaction.h.
Referenced by CollimationAction(), and screw().
The documentation for this class was generated from the following files:
CollimatorLib/model/collimationaction.h
CollimatorLib/model/collimationaction.cpp