CollimatorDesktop: RemoteTelescope Class Reference
RemoteTelescope Class Reference
#include <remotetelescope.h>
Public Member Functions
RemoteTelescope ()
RemoteTelescope (INDI::BaseDevice *device, INDI::BaseClient *client)
RemoteTelescope (QString host, int port, QString deviceName)
bool isConnected ()
bool isValid ()
int id ()
QString name ()
QString host ()
int port ()
double exposure ()
void setExposure (float exposure)
void setId (int id)
void setPort (int port)
void setName (QString name)
void setHost (QString host)
Private Attributes
int m_id
INDI::BaseDevice * m_device
QString m_host
int m_port
double m_exposure
QString m_deviceName
Detailed Description
Definition at line 8 of file remotetelescope.h.
Constructor & Destructor Documentation
RemoteTelescope() [1/3]
RemoteTelescope::RemoteTelescope ()
Definition at line 4 of file remotetelescope.cpp.
References m_deviceName, m_exposure, m_host, m_id, and m_port.
RemoteTelescope() [2/3]
RemoteTelescope::RemoteTelescope (INDI::BaseDevice * device, INDI::BaseClient * client)
Definition at line 14 of file remotetelescope.cpp.
References m_device, m_deviceName, m_exposure, m_host, m_id, and m_port.
RemoteTelescope() [3/3]
RemoteTelescope::RemoteTelescope (QString host, int port, QString deviceName)
Definition at line 25 of file remotetelescope.cpp.
References host(), m_deviceName, m_exposure, m_host, m_port, and port().
Member Function Documentation
exposure()
double RemoteTelescope::exposure ()
Definition at line 75 of file remotetelescope.cpp.
References m_exposure.
Referenced by RemoteTelescopeDAO::bindValues(), INDIClient::getImageFromTelescope(), setExposure(), and ConnectionSettingsDialog::setRemoteTelescope().
host()
QString RemoteTelescope::host ()
Definition at line 69 of file remotetelescope.cpp.
References m_host.
Referenced by RemoteTelescopeDAO::bindValues(), RemoteTelescope(), setHost(), and ConnectionSettingsDialog::setRemoteTelescope().
id()
int RemoteTelescope::id ()
Definition at line 95 of file remotetelescope.cpp.
References m_id.
Referenced by RemoteTelescopeDAO::bindValues(), RemoteTelescopeDAO::save(), setId(), and RemoteTelescopeDAO::update().
isConnected()
bool RemoteTelescope::isConnected ()
Definition at line 43 of file remotetelescope.cpp.
References m_device.
isValid()
bool RemoteTelescope::isValid ()
Definition at line 49 of file remotetelescope.cpp.
References m_deviceName, m_host, and m_port.
Referenced by TelescopeView::connectionSettings(), and TelescopeView::setTelescope().
name()
QString RemoteTelescope::name ()
Definition at line 37 of file remotetelescope.cpp.
References m_deviceName.
Referenced by RemoteTelescopeDAO::bindValues(), ConnectionSettingsDialog::deviceDetected(), INDIClient::getImageFromTelescope(), setName(), ConnectionSettingsDialog::setRemoteTelescope(), and CollimatorImage::telescopeDetected().
port()
int RemoteTelescope::port ()
Definition at line 63 of file remotetelescope.cpp.
References m_port.
Referenced by RemoteTelescopeDAO::bindValues(), RemoteTelescope(), setPort(), and ConnectionSettingsDialog::setRemoteTelescope().
setExposure()
void RemoteTelescope::setExposure (float exposure)
Definition at line 81 of file remotetelescope.cpp.
References exposure(), and m_exposure.
Referenced by RemoteTelescopeDAO::createObject(), TelescopeDAO::createObject(), and ConnectionSettingsDialog::ok().
setHost()
void RemoteTelescope::setHost (QString host)
Definition at line 117 of file remotetelescope.cpp.
References host(), and m_host.
Referenced by ConnectionSettingsDialog::ok().
setId()
void RemoteTelescope::setId (int id)
Definition at line 89 of file remotetelescope.cpp.
References id(), and m_id.
Referenced by TelescopeDAO::createObject(), and TelescopeDAO::save().
setName()
void RemoteTelescope::setName (QString name)
Definition at line 109 of file remotetelescope.cpp.
References m_deviceName, and name().
Referenced by ConnectionSettingsDialog::ok().
setPort()
void RemoteTelescope::setPort (int port)
Definition at line 101 of file remotetelescope.cpp.
References m_port, and port().
Referenced by ConnectionSettingsDialog::ok().
Member Data Documentation
m_device
INDI::BaseDevice* RemoteTelescope::m_device private
Definition at line 32 of file remotetelescope.h.
Referenced by isConnected(), and RemoteTelescope().
m_deviceName
QString RemoteTelescope::m_deviceName private
Definition at line 36 of file remotetelescope.h.
Referenced by isValid(), name(), RemoteTelescope(), and setName().
m_exposure
double RemoteTelescope::m_exposure private
Definition at line 35 of file remotetelescope.h.
Referenced by exposure(), RemoteTelescope(), and setExposure().
m_host
QString RemoteTelescope::m_host private
Definition at line 33 of file remotetelescope.h.
Referenced by host(), isValid(), RemoteTelescope(), and setHost().
m_id
int RemoteTelescope::m_id private
Definition at line 31 of file remotetelescope.h.
Referenced by id(), RemoteTelescope(), and setId().
m_port
int RemoteTelescope::m_port private
Definition at line 34 of file remotetelescope.h.
Referenced by isValid(), port(), RemoteTelescope(), and setPort().
The documentation for this class was generated from the following files:
CollimatorLib/model/remotetelescope.h
CollimatorLib/model/remotetelescope.cpp