CollimatorDesktop: CollimatorImage Class Reference
CollimatorImage Class Reference
#include <collimatorimage.h>
Classes
struct Image
Public Slots
void propertiesChanged ()
propertiesChanged Slot to be called when telescope properties are changed to refresh image
Signals
void connectedChanged (bool)
connectedChanged Signal emited when telescope is connected or disconnected
Public Member Functions
CollimatorImage (QWidget *parent=0)
~CollimatorImage ()
void setTelescope (TelescopeUI *telescope)
setTelescope Sets the telescope which is going to be used for displaying properties and drawings
void setScrollArea (QScrollArea *parentScrollArea)
setScrollArea Sets the scroll area container for better zoom
void setDebug (bool debug)
setDebug If true shows window with debug image every refresh
void loadImage (QString path)
loadImage Loads image from path
void connectTelescope (RemoteTelescope remoteTelescope)
connectTelescope Connects to the given RemoteTelescope and starts getting images
void zoom (float diff)
zoom Zoom on image
void refreshImage ()
refreshImage Reloads current image with its telescope properties
void setConnected (bool connected)
setConnected Changes connection property. If false will stop receiving images
Private Slots
void telescopeDetected (RemoteTelescope)
void imageReceived (QString)
Private Member Functions
void mousePressEvent (QMouseEvent *ev)
void mouseReleaseEvent (QMouseEvent *ev)
void displayPixmap ()
Private Attributes
struct CollimatorImage::Image image
bool dragging
QScrollArea * scrollArea
TelescopeUI * telescope
RemoteTelescope remoteTelescope
INDIClient client
bool showDebug
bool m_connected
Detailed Description
Definition at line 14 of file collimatorimage.h.
Constructor & Destructor Documentation
CollimatorImage()
CollimatorImage::CollimatorImage (QWidget * parent = 0)
Definition at line 14 of file collimatorimage.cpp.
References dragging, m_connected, showDebug, and telescope.
~CollimatorImage()
CollimatorImage::~CollimatorImage () inline
Definition at line 19 of file collimatorimage.h.
References client, INDIClient::disconnect(), and INDIClient::isConnectedToServer().
Member Function Documentation
connectedChanged
void CollimatorImage::connectedChanged (bool) signal
connectedChanged Signal emited when telescope is connected or disconnected
Referenced by setConnected(), telescopeDetected(), and TelescopeView::TelescopeView().
connectTelescope()
void CollimatorImage::connectTelescope (RemoteTelescope remoteTelescope)
connectTelescope Connects to the given RemoteTelescope and starts getting images
Parameters
remoteTelescope
Definition at line 62 of file collimatorimage.cpp.
References client, INDIClient::connectToServer(), INDIClient::deviceDetected(), remoteTelescope, telescope, and telescopeDetected().
Referenced by TelescopeView::connectTelescope().
displayPixmap()
void CollimatorImage::displayPixmap () private
imageReceived
void CollimatorImage::imageReceived (QString filePath) private slot
Definition at line 213 of file collimatorimage.cpp.
References client, INDIClient::getImageFromTelescope(), loadImage(), m_connected, and remoteTelescope.
Referenced by telescopeDetected().
loadImage()
void CollimatorImage::loadImage (QString path)
loadImage Loads image from path
Parameters
path Path of the image to be loaded
Definition at line 36 of file collimatorimage.cpp.
References CollimatorImage::Image::data, CollimatorImage::Image::format, CollimatorImage::Image::height, image, Collimator::loadFitsImage(), refreshImage(), CollimatorImage::Image::step, and CollimatorImage::Image::width.
Referenced by imageReceived(), and TelescopeView::openImageFromFile().
mousePressEvent()
void CollimatorImage::mousePressEvent (QMouseEvent * ev) private
Definition at line 167 of file collimatorimage.cpp.
References PaintingProperties::automatic(), PaintingProperties::Scope::center, dragging, TelescopeUI::paintingProperties(), PaintingProperties::scope(), PaintingProperties::setScope(), telescope, and PaintingProperties::zoom().
mouseReleaseEvent()
void CollimatorImage::mouseReleaseEvent (QMouseEvent * ev) private
Definition at line 179 of file collimatorimage.cpp.
References PaintingProperties::automatic(), PaintingProperties::Scope::center, dragging, TelescopeUI::paintingProperties(), PaintingProperties::Scope::radius, refreshImage(), PaintingProperties::scope(), PaintingProperties::setScope(), telescope, and PaintingProperties::zoom().
propertiesChanged
void CollimatorImage::propertiesChanged () slot
propertiesChanged Slot to be called when telescope properties are changed to refresh image
Definition at line 161 of file collimatorimage.cpp.
References image, refreshImage(), and CollimatorImage::Image::width.
Referenced by TelescopeView::TelescopeView().
refreshImage()
void CollimatorImage::refreshImage ()
refreshImage Reloads current image with its telescope properties
Definition at line 130 of file collimatorimage.cpp.
References PaintingProperties::automatic(), calculateScrewsDegrees(), CollimatorImage::Image::data, CollimatorImage::Image::format, CollimatorImage::Image::height, PaintingProperties::Mirroring::horizontally, image, PaintingProperties::imageMirroring(), PaintingProperties::paint(), TelescopeUI::paintingProperties(), Collimator::proccessImage(), Telescope::processingProperties(), Telescope::screws(), PaintingProperties::setImageResults(), Telescope::setScrews(), showDebug, CollimatorImage::Image::step, telescope, PaintingProperties::Mirroring::vertically, CollimatorImage::Image::width, and PaintingProperties::zoom().
Referenced by loadImage(), mouseReleaseEvent(), propertiesChanged(), and zoom().
setConnected()
void CollimatorImage::setConnected (bool connected)
setConnected Changes connection property. If false will stop receiving images
Parameters
connected
Definition at line 221 of file collimatorimage.cpp.
References client, connectedChanged(), INDIClient::disconnect(), and m_connected.
Referenced by TelescopeView::disconnectTelescope().
setDebug()
void CollimatorImage::setDebug (bool debug)
setDebug If true shows window with debug image every refresh
Definition at line 196 of file collimatorimage.cpp.
References showDebug.
Referenced by TelescopeView::changeProperties().
setScrollArea()
void CollimatorImage::setScrollArea (QScrollArea * parentScrollArea)
setScrollArea Sets the scroll area container for better zoom
Parameters
parentScrollArea Parent QScrollAreal
Definition at line 30 of file collimatorimage.cpp.
References scrollArea.
Referenced by TelescopeView::TelescopeView().
setTelescope()
void CollimatorImage::setTelescope (TelescopeUI * telescope)
setTelescope Sets the telescope which is going to be used for displaying properties and drawings
Parameters
telescope
Definition at line 24 of file collimatorimage.cpp.
References telescope.
Referenced by TelescopeView::TelescopeView().
telescopeDetected
void CollimatorImage::telescopeDetected (RemoteTelescope detectedTelescope) private slot
Definition at line 202 of file collimatorimage.cpp.
References client, connectedChanged(), INDIClient::getImageFromTelescope(), INDIClient::imageReceived(), imageReceived(), m_connected, RemoteTelescope::name(), and remoteTelescope.
Referenced by connectTelescope().
zoom()
void CollimatorImage::zoom (float diff)
zoom Zoom on image
Parameters
diff Float value of the zoom diff to do. If negative will unzoom
Definition at line 69 of file collimatorimage.cpp.
References TelescopeUI::paintingProperties(), refreshImage(), scrollArea, PaintingProperties::setZoom(), telescope, and PaintingProperties::zoom().
Referenced by TelescopeView::TelescopeView().
Member Data Documentation
client
INDIClient CollimatorImage::client private
Definition at line 90 of file collimatorimage.h.
Referenced by connectTelescope(), imageReceived(), setConnected(), telescopeDetected(), and ~CollimatorImage().
dragging
bool CollimatorImage::dragging private
Definition at line 85 of file collimatorimage.h.
Referenced by CollimatorImage(), mousePressEvent(), and mouseReleaseEvent().
image
struct CollimatorImage::Image CollimatorImage::image private
Referenced by loadImage(), propertiesChanged(), and refreshImage().
m_connected
bool CollimatorImage::m_connected private
Definition at line 92 of file collimatorimage.h.
Referenced by CollimatorImage(), imageReceived(), setConnected(), and telescopeDetected().
remoteTelescope
RemoteTelescope CollimatorImage::remoteTelescope private
Definition at line 89 of file collimatorimage.h.
Referenced by connectTelescope(), imageReceived(), and telescopeDetected().
scrollArea
QScrollArea* CollimatorImage::scrollArea private
Definition at line 87 of file collimatorimage.h.
Referenced by setScrollArea(), and zoom().
showDebug
bool CollimatorImage::showDebug private
Definition at line 91 of file collimatorimage.h.
Referenced by CollimatorImage(), refreshImage(), and setDebug().
telescope
TelescopeUI* CollimatorImage::telescope private
Definition at line 88 of file collimatorimage.h.
Referenced by CollimatorImage(), connectTelescope(), mousePressEvent(), mouseReleaseEvent(), refreshImage(), setTelescope(), and zoom().
The documentation for this class was generated from the following files:
logic/collimatorimage.h
logic/collimatorimage.cpp