CollimatorDesktop: PaintingProperties Class Reference
PaintingProperties Class Reference
The PaintingProperties class defines the properties for painting automatic and manual drawings of a collimation result.
#include <paintingproperties.h>
Classes
struct Mirroring
struct Scope
Public Member Functions
PaintingProperties ()
void setId (int id)
void setScrewsRadius (int screwsRadius)
void setZoom (float zoom)
void setAutomatic (bool automatic)
void setViewBoundingBox (bool boundingBox)
void setViewScrews (bool viewScrews)
void setViewCalculatedCenter (bool viewCalculatedCenter)
void setImageResults (ImageResults *imageResults)
void setScope (Scope scope)
void setImageMirroring (Mirroring imageMirroring)
void setScrewsMirroring (Mirroring screwsMirroring)
void setTigthMirroring (bool tightMirroring)
int id ()
int screwsRadius ()
float zoom ()
bool automatic ()
bool viewBoundingBox ()
bool viewScrews ()
bool viewCalculatedCenter ()
bool tightMirroring ()
Scope scope ()
Mirroring imageMirroring ()
Mirroring screwsMirroring ()
void paint (QImage *image, Telescope telescope)
paint Paints into image own properties of the telescope
Private Member Functions
void paintScrewsHelp (Telescope telescope, QPoint center, QPainter *painter)
Private Attributes
Scope m_scope
Mirroring m_imageMirroring
Mirroring m_screwsMirroring
int m_id
int m_screwsRadius
float m_zoom
bool m_automatic
bool m_viewBoundingBox
bool m_viewCalculatedCenter
bool m_viewScrews
bool m_tightMirroring
ImageResults * m_imageResults
Detailed Description
The PaintingProperties class defines the properties for painting automatic and manual drawings of a collimation result.
Definition at line 11 of file paintingproperties.h.
Constructor & Destructor Documentation
PaintingProperties()
PaintingProperties::PaintingProperties ()
Definition at line 7 of file paintingproperties.cpp.
References PaintingProperties::Mirroring::horizontally, m_automatic, m_imageMirroring, m_scope, m_screwsMirroring, m_screwsRadius, m_tightMirroring, m_viewBoundingBox, m_viewCalculatedCenter, m_viewScrews, m_zoom, PaintingProperties::Scope::radius, and PaintingProperties::Mirroring::vertically.
Member Function Documentation
automatic()
bool PaintingProperties::automatic ()
Definition at line 116 of file paintingproperties.cpp.
References m_automatic.
Referenced by PaintingPropertiesDAO::bindValues(), CollimatorImage::mousePressEvent(), CollimatorImage::mouseReleaseEvent(), CollimatorImage::refreshImage(), setAutomatic(), and TelescopeView::setTelescope().
id()
int PaintingProperties::id ()
Definition at line 100 of file paintingproperties.cpp.
References m_id.
Referenced by PaintingPropertiesDAO::save(), setId(), and PaintingPropertiesDAO::update().
imageMirroring()
PaintingProperties::Mirroring PaintingProperties::imageMirroring ()
Definition at line 146 of file paintingproperties.cpp.
References m_imageMirroring.
Referenced by PaintingPropertiesDAO::bindValues(), CollimatorImage::refreshImage(), setImageMirroring(), and TelescopeView::setTelescope().
paint()
void PaintingProperties::paint (QImage * image, Telescope telescope)
paint Paints into image own properties of the telescope
Parameters
image Image where to draw
telescope
Definition at line 237 of file paintingproperties.cpp.
References ImageResults::boundingBox(), ImageResults::center(), PaintingProperties::Scope::center, ImageResults::Rect::heigth, m_automatic, m_imageResults, m_scope, m_screwsRadius, m_viewBoundingBox, m_viewCalculatedCenter, m_viewScrews, paintScrewsHelp(), PaintingProperties::Scope::radius, Telescope::screws(), ImageResults::Rect::width, ImageResults::Point::x, ImageResults::Rect::x, ImageResults::Point::y, and ImageResults::Rect::y.
Referenced by CollimatorImage::refreshImage().
paintScrewsHelp()
void PaintingProperties::paintScrewsHelp (Telescope telescope, QPoint center, QPainter * painter) private
Definition at line 179 of file paintingproperties.cpp.
References CollimationAction::action(), Screw::degrees(), ImageResults::getAction(), Screw::getScrewPosition(), CollimationAction::Loosen, m_imageResults, m_screwsRadius, rotatePoint(), CollimationAction::screw(), CollimationAction::Tighten, and tightMirroring().
Referenced by paint().
scope()
PaintingProperties::Scope PaintingProperties::scope ()
Definition at line 140 of file paintingproperties.cpp.
References m_scope.
Referenced by PaintingPropertiesDAO::bindValues(), CollimatorImage::mousePressEvent(), CollimatorImage::mouseReleaseEvent(), and setScope().
screwsMirroring()
PaintingProperties::Mirroring PaintingProperties::screwsMirroring ()
Definition at line 158 of file paintingproperties.cpp.
References m_screwsMirroring.
Referenced by PaintingPropertiesDAO::bindValues(), calculateScrewsDegrees(), setScrewsMirroring(), and TelescopeView::setTelescope().
screwsRadius()
int PaintingProperties::screwsRadius ()
Definition at line 105 of file paintingproperties.cpp.
References m_screwsRadius.
Referenced by PaintingPropertiesDAO::bindValues(), TelescopeView::screwsSettings(), and setScrewsRadius().
setAutomatic()
void PaintingProperties::setAutomatic (bool automatic)
Definition at line 46 of file paintingproperties.cpp.
References automatic(), and m_automatic.
Referenced by PaintingPropertiesDAO::createObject(), TelescopeDAO::createObject(), and TelescopeView::setAutomatic().
setId()
void PaintingProperties::setId (int id)
Definition at line 28 of file paintingproperties.cpp.
References id(), and m_id.
Referenced by PaintingPropertiesDAO::createObject(), TelescopeDAO::createObject(), and TelescopeDAO::save().
setImageMirroring()
void PaintingProperties::setImageMirroring (Mirroring imageMirroring)
Definition at line 82 of file paintingproperties.cpp.
References imageMirroring(), and m_imageMirroring.
Referenced by TelescopeView::changeProperties(), PaintingPropertiesDAO::createObject(), and TelescopeDAO::createObject().
setImageResults()
void PaintingProperties::setImageResults (ImageResults * imageResults)
Definition at line 70 of file paintingproperties.cpp.
References m_imageResults.
Referenced by CollimatorImage::refreshImage().
setScope()
void PaintingProperties::setScope (Scope scope)
Definition at line 76 of file paintingproperties.cpp.
References m_scope, and scope().
Referenced by PaintingPropertiesDAO::createObject(), TelescopeDAO::createObject(), CollimatorImage::mousePressEvent(), and CollimatorImage::mouseReleaseEvent().
setScrewsMirroring()
void PaintingProperties::setScrewsMirroring (Mirroring screwsMirroring)
Definition at line 88 of file paintingproperties.cpp.
References m_screwsMirroring, and screwsMirroring().
Referenced by TelescopeView::changeProperties(), PaintingPropertiesDAO::createObject(), and TelescopeDAO::createObject().
setScrewsRadius()
void PaintingProperties::setScrewsRadius (int screwsRadius)
Definition at line 34 of file paintingproperties.cpp.
References m_screwsRadius, and screwsRadius().
Referenced by PaintingPropertiesDAO::createObject(), TelescopeDAO::createObject(), and TelescopeView::screwsSettings().
setTigthMirroring()
void PaintingProperties::setTigthMirroring (bool tightMirroring)
Definition at line 94 of file paintingproperties.cpp.
References m_tightMirroring, and tightMirroring().
Referenced by TelescopeView::changeProperties(), PaintingPropertiesDAO::createObject(), and TelescopeDAO::createObject().
setViewBoundingBox()
void PaintingProperties::setViewBoundingBox (bool boundingBox)
Definition at line 52 of file paintingproperties.cpp.
References m_viewBoundingBox, and viewBoundingBox().
Referenced by TelescopeView::changeProperties(), PaintingPropertiesDAO::createObject(), and TelescopeDAO::createObject().
setViewCalculatedCenter()
void PaintingProperties::setViewCalculatedCenter (bool viewCalculatedCenter)
Definition at line 64 of file paintingproperties.cpp.
References m_viewCalculatedCenter, and viewCalculatedCenter().
Referenced by TelescopeView::changeProperties(), PaintingPropertiesDAO::createObject(), and TelescopeDAO::createObject().
setViewScrews()
void PaintingProperties::setViewScrews (bool viewScrews)
Definition at line 58 of file paintingproperties.cpp.
References m_viewScrews, and viewScrews().
Referenced by TelescopeView::changeProperties(), PaintingPropertiesDAO::createObject(), and TelescopeDAO::createObject().
setZoom()
void PaintingProperties::setZoom (float zoom)
Definition at line 40 of file paintingproperties.cpp.
References m_zoom, and zoom().
Referenced by PaintingPropertiesDAO::createObject(), TelescopeDAO::createObject(), and CollimatorImage::zoom().
tightMirroring()
bool PaintingProperties::tightMirroring ()
Definition at line 152 of file paintingproperties.cpp.
References m_tightMirroring.
Referenced by PaintingPropertiesDAO::bindValues(), paintScrewsHelp(), TelescopeView::setTelescope(), and setTigthMirroring().
viewBoundingBox()
bool PaintingProperties::viewBoundingBox ()
Definition at line 122 of file paintingproperties.cpp.
References m_viewBoundingBox.
Referenced by PaintingPropertiesDAO::bindValues(), TelescopeView::setTelescope(), and setViewBoundingBox().
viewCalculatedCenter()
bool PaintingProperties::viewCalculatedCenter ()
Definition at line 134 of file paintingproperties.cpp.
References m_viewCalculatedCenter.
Referenced by PaintingPropertiesDAO::bindValues(), TelescopeView::setTelescope(), and setViewCalculatedCenter().
viewScrews()
bool PaintingProperties::viewScrews ()
Definition at line 128 of file paintingproperties.cpp.
References m_viewScrews.
Referenced by PaintingPropertiesDAO::bindValues(), TelescopeView::setTelescope(), and setViewScrews().
zoom()
float PaintingProperties::zoom ()
Definition at line 110 of file paintingproperties.cpp.
References m_zoom.
Referenced by PaintingPropertiesDAO::bindValues(), CollimatorImage::mousePressEvent(), CollimatorImage::mouseReleaseEvent(), CollimatorImage::refreshImage(), setZoom(), and CollimatorImage::zoom().
Member Data Documentation
m_automatic
bool PaintingProperties::m_automatic private
Definition at line 64 of file paintingproperties.h.
Referenced by automatic(), paint(), PaintingProperties(), and setAutomatic().
m_id
int PaintingProperties::m_id private
Definition at line 61 of file paintingproperties.h.
Referenced by id(), and setId().
m_imageMirroring
Mirroring PaintingProperties::m_imageMirroring private
Definition at line 58 of file paintingproperties.h.
Referenced by imageMirroring(), PaintingProperties(), and setImageMirroring().
m_imageResults
ImageResults* PaintingProperties::m_imageResults private
Definition at line 69 of file paintingproperties.h.
Referenced by paint(), paintScrewsHelp(), and setImageResults().
m_scope
Scope PaintingProperties::m_scope private
Definition at line 57 of file paintingproperties.h.
Referenced by paint(), PaintingProperties(), scope(), and setScope().
m_screwsMirroring
Mirroring PaintingProperties::m_screwsMirroring private
Definition at line 59 of file paintingproperties.h.
Referenced by PaintingProperties(), screwsMirroring(), and setScrewsMirroring().
m_screwsRadius
int PaintingProperties::m_screwsRadius private
Definition at line 62 of file paintingproperties.h.
Referenced by paint(), PaintingProperties(), paintScrewsHelp(), screwsRadius(), and setScrewsRadius().
m_tightMirroring
bool PaintingProperties::m_tightMirroring private
Definition at line 68 of file paintingproperties.h.
Referenced by PaintingProperties(), setTigthMirroring(), and tightMirroring().
m_viewBoundingBox
bool PaintingProperties::m_viewBoundingBox private
Definition at line 65 of file paintingproperties.h.
Referenced by paint(), PaintingProperties(), setViewBoundingBox(), and viewBoundingBox().
m_viewCalculatedCenter
bool PaintingProperties::m_viewCalculatedCenter private
Definition at line 66 of file paintingproperties.h.
Referenced by paint(), PaintingProperties(), setViewCalculatedCenter(), and viewCalculatedCenter().
m_viewScrews
bool PaintingProperties::m_viewScrews private
Definition at line 67 of file paintingproperties.h.
Referenced by paint(), PaintingProperties(), setViewScrews(), and viewScrews().
m_zoom
float PaintingProperties::m_zoom private
Definition at line 63 of file paintingproperties.h.
Referenced by PaintingProperties(), setZoom(), and zoom().
The documentation for this class was generated from the following files:
logic/paintingproperties.h
logic/paintingproperties.cpp