CollimatorDesktop: TelescopeDAO Class Reference
TelescopeDAO Class Reference
#include <telescopedao.h>
Public Member Functions
int save (TelescopeUI *)
TelescopeDAO::save Method for saving an insance of a Telescope.
int update (TelescopeUI)
update Method for updating an instance of a telescope. Also updates or creates other objects that a telescope contains
TelescopeUI get (int id)
get Method for obtaining a Telescope by id
QList< TelescopeUI > getAll ()
getAll Method for obtaining all Telescopes in the database
bool remove (int id)
remove Method for removing a Telescope by id
Static Private Member Functions
static TelescopeUI createObject (QSqlQuery query)
createObject Private method for getting Telescope object using a row of a query
Private Attributes
DatabaseConnectionSingleton db = DatabaseConnectionSingleton::instance()
Detailed Description
Definition at line 7 of file telescopedao.h.
Member Function Documentation
createObject()
TelescopeUI TelescopeDAO::createObject (QSqlQuery query) static private
createObject Private method for getting Telescope object using a row of a query
Parameters
query Query with values
Returns
Telescope given the data from the current row of the query
Definition at line 209 of file telescopedao.cpp.
References PaintingProperties::Scope::center, ProcessingProperties::ThresholdValues::constant, PaintingProperties::Mirroring::horizontally, ProcessingProperties::StretchingValues::max, ProcessingProperties::StretchingValues::min, PaintingProperties::Scope::radius, PaintingProperties::setAutomatic(), RemoteTelescope::setExposure(), ProcessingProperties::setId(), RemoteTelescope::setId(), Telescope::setId(), PaintingProperties::setId(), PaintingProperties::setImageMirroring(), Telescope::setName(), TelescopeUI::setPaintingProperties(), Telescope::setProcessingProperties(), ProcessingProperties::setRefinateRadius(), Telescope::setRemoteTelescope(), ProcessingProperties::setScale(), PaintingProperties::setScope(), PaintingProperties::setScrewsMirroring(), PaintingProperties::setScrewsRadius(), ProcessingProperties::setStretchingValues(), ProcessingProperties::setThresholdValues(), PaintingProperties::setTigthMirroring(), PaintingProperties::setViewBoundingBox(), PaintingProperties::setViewCalculatedCenter(), PaintingProperties::setViewScrews(), PaintingProperties::setZoom(), ProcessingProperties::ThresholdValues::thresholdSize, and PaintingProperties::Mirroring::vertically.
Referenced by getAll().
get()
TelescopeUI TelescopeDAO::get (int id)
get Method for obtaining a Telescope by id
Parameters
id Id of the telescope to be obtained
Returns
Telescope mathcing id
Definition at line 102 of file telescopedao.cpp.
References db, PaintingPropertiesDAO::get(), ProcessingPropertiesDAO::get(), RemoteTelescopeDAO::get(), DatabaseConnectionSingleton::getDatabase(), Screw::setDegrees(), Screw::setId(), Telescope::setId(), Telescope::setName(), TelescopeUI::setPaintingProperties(), Telescope::setProcessingProperties(), Telescope::setRemoteTelescope(), and Telescope::setScrews().
getAll()
QList< TelescopeUI > TelescopeDAO::getAll ()
getAll Method for obtaining all Telescopes in the database
Returns
QList<Telescope> List of all telescopes
Definition at line 145 of file telescopedao.cpp.
References createObject(), db, DatabaseConnectionSingleton::getDatabase(), Screw::setDegrees(), and Screw::setId().
Referenced by TelescopeSelector::TelescopeSelector().
remove()
bool TelescopeDAO::remove (int id)
remove Method for removing a Telescope by id
Parameters
id Id of the telescope to be removed
Returns
bool indicating if removing was successful
Definition at line 194 of file telescopedao.cpp.
References db, and DatabaseConnectionSingleton::getDatabase().
Referenced by TelescopeSelector::removeTelescope().
save()
int TelescopeDAO::save (TelescopeUI * telescope)
TelescopeDAO::save Method for saving an insance of a Telescope.
Parameters
telescope Telescope to be saved
Returns
id of the saved Telescope. -1 if error
Definition at line 6 of file telescopedao.cpp.
References db, DatabaseConnectionSingleton::getDatabase(), Telescope::id(), Telescope::name(), TelescopeUI::paintingProperties(), Telescope::processingProperties(), Telescope::remoteTelescope(), PaintingPropertiesDAO::save(), ProcessingPropertiesDAO::save(), RemoteTelescopeDAO::save(), Telescope::screws(), ProcessingProperties::setId(), RemoteTelescope::setId(), Telescope::setId(), PaintingProperties::setId(), TelescopeUI::setPaintingProperties(), Telescope::setProcessingProperties(), and Telescope::setRemoteTelescope().
Referenced by TelescopeSelector::createTelescope().
update()
int TelescopeDAO::update (TelescopeUI telescope)
update Method for updating an instance of a telescope. Also updates or creates other objects that a telescope contains
Parameters
telescope to be updated
Returns
int Id of the Telescope. -1 if error
Definition at line 56 of file telescopedao.cpp.
References db, DatabaseConnectionSingleton::getDatabase(), Telescope::id(), Telescope::name(), TelescopeUI::paintingProperties(), Telescope::processingProperties(), Telescope::remoteTelescope(), Telescope::screws(), PaintingPropertiesDAO::update(), ProcessingPropertiesDAO::update(), and RemoteTelescopeDAO::update().
Referenced by TelescopeView::saveTelescope(), and TelescopeView::screwsSettings().
Member Data Documentation
db
DatabaseConnectionSingleton TelescopeDAO::db = DatabaseConnectionSingleton::instance() private
Definition at line 51 of file telescopedao.h.
Referenced by get(), getAll(), remove(), save(), and update().
The documentation for this class was generated from the following files:
persistence/telescopedao.h
persistence/telescopedao.cpp