CollimatorDesktop: ProcessingProperties Class Reference
ProcessingProperties Class Reference
#include <processingproperties.h>
Classes
struct StretchingValues
struct ThresholdValues
Public Member Functions
ProcessingProperties (ProcessingProperties *proccessingProperties)
ProcessingProperties ()
int id ()
float scale ()
float refinateRadius ()
StretchingValues stretchingValues ()
ThresholdValues thresholdValues ()
void setId (int id)
void setScale (float scale)
void setRefinateRadius (float refinateRadius)
void setStretchingValues (StretchingValues values)
void setThresholdValues (ThresholdValues values)
ProcessingProperties::setThresholdValues.
Private Attributes
int m_id
float m_scale
float m_refinateRadius
StretchingValues m_stretchingValues
ThresholdValues m_thresholdValues
Detailed Description
Definition at line 6 of file processingproperties.h.
Constructor & Destructor Documentation
ProcessingProperties() [1/2]
ProcessingProperties::ProcessingProperties (ProcessingProperties * proccessingProperties) explicit
Definition at line 4 of file processingproperties.cpp.
References m_id, m_refinateRadius, m_scale, m_stretchingValues, m_thresholdValues, refinateRadius(), scale(), stretchingValues(), and thresholdValues().
ProcessingProperties() [2/2]
ProcessingProperties::ProcessingProperties () explicit
Definition at line 13 of file processingproperties.cpp.
References ProcessingProperties::ThresholdValues::constant, m_id, m_refinateRadius, m_scale, m_stretchingValues, m_thresholdValues, ProcessingProperties::StretchingValues::max, ProcessingProperties::StretchingValues::min, and ProcessingProperties::ThresholdValues::thresholdSize.
Member Function Documentation
id()
int ProcessingProperties::id ()
Definition at line 67 of file processingproperties.cpp.
References m_id.
Referenced by ProcessingPropertiesDAO::save(), setId(), and ProcessingPropertiesDAO::update().
refinateRadius()
float ProcessingProperties::refinateRadius ()
Definition at line 77 of file processingproperties.cpp.
References m_refinateRadius.
Referenced by ProcessingPropertiesDAO::bindValues(), Collimator::proccessImage(), ProcessingProperties(), setRefinateRadius(), and ProcessingPropertiesSettings::setValuesOnScreen().
scale()
float ProcessingProperties::scale ()
Definition at line 72 of file processingproperties.cpp.
References m_scale.
Referenced by ProcessingPropertiesDAO::bindValues(), Collimator::proccessImage(), ProcessingProperties(), and setScale().
setId()
void ProcessingProperties::setId (int id)
Definition at line 25 of file processingproperties.cpp.
References id(), and m_id.
Referenced by ProcessingPropertiesDAO::createObject(), TelescopeDAO::createObject(), and TelescopeDAO::save().
setRefinateRadius()
void ProcessingProperties::setRefinateRadius (float refinateRadius)
Definition at line 38 of file processingproperties.cpp.
References m_refinateRadius, and refinateRadius().
Referenced by ProcessingPropertiesDAO::createObject(), TelescopeDAO::createObject(), and ProcessingPropertiesSettings::processingProperties().
setScale()
void ProcessingProperties::setScale (float scale)
Definition at line 30 of file processingproperties.cpp.
References m_scale, and scale().
Referenced by ProcessingPropertiesDAO::createObject(), and TelescopeDAO::createObject().
setStretchingValues()
void ProcessingProperties::setStretchingValues (StretchingValues values)
Definition at line 43 of file processingproperties.cpp.
References m_stretchingValues, ProcessingProperties::StretchingValues::max, and ProcessingProperties::StretchingValues::min.
Referenced by ProcessingPropertiesDAO::createObject(), TelescopeDAO::createObject(), and ProcessingPropertiesSettings::processingProperties().
setThresholdValues()
void ProcessingProperties::setThresholdValues (ThresholdValues values)
ProcessingProperties::setThresholdValues.
Parameters
values size: 3,5,7,9... constant cualquiera, normalmente positivo
Definition at line 57 of file processingproperties.cpp.
References m_thresholdValues, and ProcessingProperties::ThresholdValues::thresholdSize.
Referenced by ProcessingPropertiesDAO::createObject(), TelescopeDAO::createObject(), and ProcessingPropertiesSettings::processingProperties().
stretchingValues()
ProcessingProperties::StretchingValues ProcessingProperties::stretchingValues ()
Definition at line 82 of file processingproperties.cpp.
References m_stretchingValues.
Referenced by ProcessingPropertiesDAO::bindValues(), Collimator::proccessImage(), ProcessingProperties(), and ProcessingPropertiesSettings::setValuesOnScreen().
thresholdValues()
ProcessingProperties::ThresholdValues ProcessingProperties::thresholdValues ()
Definition at line 87 of file processingproperties.cpp.
References m_thresholdValues.
Referenced by ProcessingPropertiesDAO::bindValues(), Collimator::proccessImage(), ProcessingProperties(), and ProcessingPropertiesSettings::setValuesOnScreen().
Member Data Documentation
m_id
int ProcessingProperties::m_id private
Definition at line 36 of file processingproperties.h.
Referenced by id(), ProcessingProperties(), and setId().
m_refinateRadius
float ProcessingProperties::m_refinateRadius private
Definition at line 38 of file processingproperties.h.
Referenced by ProcessingProperties(), refinateRadius(), and setRefinateRadius().
m_scale
float ProcessingProperties::m_scale private
Definition at line 37 of file processingproperties.h.
Referenced by ProcessingProperties(), scale(), and setScale().
m_stretchingValues
StretchingValues ProcessingProperties::m_stretchingValues private
Definition at line 39 of file processingproperties.h.
Referenced by ProcessingProperties(), setStretchingValues(), and stretchingValues().
m_thresholdValues
ThresholdValues ProcessingProperties::m_thresholdValues private
Definition at line 40 of file processingproperties.h.
Referenced by ProcessingProperties(), setThresholdValues(), and thresholdValues().
The documentation for this class was generated from the following files:
CollimatorLib/model/processingproperties.h
CollimatorLib/model/processingproperties.cpp