CollimatorDesktop: ScrewsDialog Class Reference
ScrewsDialog Class Reference
#include <screwsdialog.h>
Public Member Functions
ScrewsDialog (QWidget *parent=nullptr)
~ScrewsDialog ()
void setScrews (QList< Screw > screws)
setScrews Sets the Screws list from where to show the data
void setRadius (int radius)
setRadius Sets the radius of the screws
int radius ()
radius Returns the current radius with values from UI input
QList< Screw > screws ()
screws Returns the current list of screws from UI input
Private Slots
void addScrew ()
void removeScrew ()
Private Member Functions
void loadItems ()
Private Attributes
Ui::ScrewsDialog * ui
QList< Screw > m_screws
Detailed Description
Definition at line 11 of file screwsdialog.h.
Constructor & Destructor Documentation
ScrewsDialog()
ScrewsDialog::ScrewsDialog (QWidget * parent = nullptr) explicit
Definition at line 6 of file screwsdialog.cpp.
References addScrew(), loadItems(), removeScrew(), and ui.
~ScrewsDialog()
ScrewsDialog::~ScrewsDialog ()
Definition at line 18 of file screwsdialog.cpp.
References ui.
Member Function Documentation
addScrew
void ScrewsDialog::addScrew () private slot
Definition at line 57 of file screwsdialog.cpp.
References loadItems(), m_screws, and Screw::setDegrees().
Referenced by ScrewsDialog().
loadItems()
void ScrewsDialog::loadItems () private
Definition at line 49 of file screwsdialog.cpp.
References m_screws, and ui.
Referenced by addScrew(), removeScrew(), ScrewsDialog(), and setScrews().
radius()
int ScrewsDialog::radius ()
radius Returns the current radius with values from UI input
Returns
Radius from UI input
Definition at line 43 of file screwsdialog.cpp.
References ui.
Referenced by TelescopeView::screwsSettings(), and setRadius().
removeScrew
void ScrewsDialog::removeScrew () private slot
Definition at line 71 of file screwsdialog.cpp.
References loadItems(), m_screws, and ui.
Referenced by ScrewsDialog().
screws()
QList< Screw > ScrewsDialog::screws ()
screws Returns the current list of screws from UI input
Returns
Screw List from UI input
Definition at line 31 of file screwsdialog.cpp.
References m_screws.
Referenced by TelescopeView::screwsSettings(), and setScrews().
setRadius()
void ScrewsDialog::setRadius (int radius)
setRadius Sets the radius of the screws
Parameters
radius Radius of the screws
Definition at line 37 of file screwsdialog.cpp.
References radius(), and ui.
Referenced by TelescopeView::screwsSettings().
setScrews()
void ScrewsDialog::setScrews (QList< Screw > screws)
setScrews Sets the Screws list from where to show the data
Parameters
screws Screws list
Definition at line 24 of file screwsdialog.cpp.
References loadItems(), m_screws, and screws().
Referenced by TelescopeView::screwsSettings().
Member Data Documentation
m_screws
QList<Screw> ScrewsDialog::m_screws private
Definition at line 48 of file screwsdialog.h.
Referenced by addScrew(), loadItems(), removeScrew(), screws(), and setScrews().
ui
Ui::ScrewsDialog* ScrewsDialog::ui private
Definition at line 47 of file screwsdialog.h.
Referenced by loadItems(), radius(), removeScrew(), ScrewsDialog(), setRadius(), and ~ScrewsDialog().
The documentation for this class was generated from the following files:
views/screwsdialog.h
views/screwsdialog.cpp