CollimatorDesktop: ProcessingPropertiesDAO Class Reference
ProcessingPropertiesDAO Class Reference
#include <processingpropertiesdao.h>
Public Member Functions
int save (ProcessingProperties *processingProperties)
save Method for saving an instance of processingProperties
int update (ProcessingProperties processingProperties)
update Method for updating Processing Properties
ProcessingProperties get (int id)
get Method for obtaining Processing properties by id
QList< ProcessingProperties > getAll ()
getAll Method for obtaining all Processing Properties in the database
bool remove (int id)
remove Method for removing Processing properties by id
Static Public Member Functions
static ProcessingProperties createObject (QSqlQuery query)
createObject Method for getting ProcessingProperties object using a row of a query
Static Private Member Functions
static void bindValues (QSqlQuery *query, ProcessingProperties processingProperties)
bindValues Private method for binding values of the query with Processing properties to reduce code
Private Attributes
DatabaseConnectionSingleton db = DatabaseConnectionSingleton::instance()
Detailed Description
Definition at line 6 of file processingpropertiesdao.h.
Member Function Documentation
bindValues()
void ProcessingPropertiesDAO::bindValues (QSqlQuery * query, ProcessingProperties processingProperties) static private
bindValues Private method for binding values of the query with Processing properties to reduce code
Parameters
query Query where to replace data
processingProperties Processing properties from where to get data
Definition at line 84 of file processingpropertiesdao.cpp.
References ProcessingProperties::ThresholdValues::constant, ProcessingProperties::StretchingValues::max, ProcessingProperties::StretchingValues::min, ProcessingProperties::refinateRadius(), ProcessingProperties::scale(), ProcessingProperties::stretchingValues(), ProcessingProperties::ThresholdValues::thresholdSize, and ProcessingProperties::thresholdValues().
Referenced by save(), and update().
createObject()
ProcessingProperties ProcessingPropertiesDAO::createObject (QSqlQuery query) static
createObject Method for getting ProcessingProperties object using a row of a query
Parameters
query Query with values
Returns
ProcessingProperties given the data from the current row of the query
Definition at line 95 of file processingpropertiesdao.cpp.
References ProcessingProperties::ThresholdValues::constant, ProcessingProperties::StretchingValues::max, ProcessingProperties::StretchingValues::min, ProcessingProperties::setId(), ProcessingProperties::setRefinateRadius(), ProcessingProperties::setScale(), ProcessingProperties::setStretchingValues(), ProcessingProperties::setThresholdValues(), and ProcessingProperties::ThresholdValues::thresholdSize.
Referenced by get(), and getAll().
get()
ProcessingProperties ProcessingPropertiesDAO::get (int id)
get Method for obtaining Processing properties by id
Parameters
id Id of the processing properties to be obtained
Returns
ProcessingProperties Processing properties matching id
Definition at line 44 of file processingpropertiesdao.cpp.
References createObject(), db, and DatabaseConnectionSingleton::getDatabase().
Referenced by TelescopeDAO::get().
getAll()
QList< ProcessingProperties > ProcessingPropertiesDAO::getAll ()
getAll Method for obtaining all Processing Properties in the database
Returns
QList<ProcessingProperties> List of all Processing Properties in the database
Definition at line 56 of file processingpropertiesdao.cpp.
References createObject(), db, and DatabaseConnectionSingleton::getDatabase().
remove()
bool ProcessingPropertiesDAO::remove (int id)
remove Method for removing Processing properties by id
Parameters
id Id of the processing properties to be removed
Returns
bool indicating if removing was successful
Definition at line 71 of file processingpropertiesdao.cpp.
References db, and DatabaseConnectionSingleton::getDatabase().
save()
int ProcessingPropertiesDAO::save (ProcessingProperties * processingProperties)
save Method for saving an instance of processingProperties
Parameters
processingProperties Processing properties to be saved
Returns
int id of the saved Processing properties. -1 if error.
Definition at line 3 of file processingpropertiesdao.cpp.
References bindValues(), db, DatabaseConnectionSingleton::getDatabase(), and ProcessingProperties::id().
Referenced by TelescopeDAO::save().
update()
int ProcessingPropertiesDAO::update (ProcessingProperties processingProperties)
update Method for updating Processing Properties
Parameters
processingProperties Processing properties to be updated
Returns
int id of the processing properites. -1 if error
Definition at line 24 of file processingpropertiesdao.cpp.
References bindValues(), db, DatabaseConnectionSingleton::getDatabase(), and ProcessingProperties::id().
Referenced by TelescopeView::openImageProcessing(), and TelescopeDAO::update().
Member Data Documentation
db
DatabaseConnectionSingleton ProcessingPropertiesDAO::db = DatabaseConnectionSingleton::instance() private
Definition at line 57 of file processingpropertiesdao.h.
Referenced by get(), getAll(), remove(), save(), and update().
The documentation for this class was generated from the following files:
persistence/processingpropertiesdao.h
persistence/processingpropertiesdao.cpp