CollimatorDesktop: RemoteTelescopeDAO Class Reference
RemoteTelescopeDAO Class Reference
#include <remotetelescopedao.h>
Public Member Functions
int save (RemoteTelescope remoteTelescope)
save Method for saving an instance of RemoteTelescope
int update (RemoteTelescope remoteTelescope)
update Method for updating a Remote Telescope
RemoteTelescope get (int id)
get Method for obtaining Remote Telescope by id
QList< RemoteTelescope > getAll ()
getAll Method for obtaining all Remote Telescopes in the database
bool remove (int id)
remove Method for removing Remote telescope by id
Static Public Member Functions
static RemoteTelescope createObject (QSqlQuery query)
createObject Method for getting RemoteTelescope
Private Member Functions
void bindValues (QSqlQuery *query, RemoteTelescope remoteTelescope)
bindValues Private method for binding values of the query with RemoteTelescope to reduce code
Private Attributes
DatabaseConnectionSingleton db = DatabaseConnectionSingleton::instance()
Detailed Description
Definition at line 10 of file remotetelescopedao.h.
Member Function Documentation
bindValues()
void RemoteTelescopeDAO::bindValues (QSqlQuery * query, RemoteTelescope remoteTelescope) private
bindValues Private method for binding values of the query with RemoteTelescope to reduce code
Parameters
query Query where to replace data
remoteTelescope Remote Telescope from where to get data
Definition at line 95 of file remotetelescopedao.cpp.
References RemoteTelescope::exposure(), RemoteTelescope::host(), RemoteTelescope::id(), RemoteTelescope::name(), and RemoteTelescope::port().
Referenced by save(), and update().
createObject()
RemoteTelescope RemoteTelescopeDAO::createObject (QSqlQuery query) static
createObject Method for getting RemoteTelescope
Parameters
query Query with values
Returns
RemoteTelescope given the data from the current row of the query
Definition at line 81 of file remotetelescopedao.cpp.
References RemoteTelescope::setExposure().
Referenced by get(), and getAll().
get()
RemoteTelescope RemoteTelescopeDAO::get (int id)
get Method for obtaining Remote Telescope by id
Parameters
id Id of the Remote Telescope to be obtained
Returns
RemoteTelescope Remote telescope matching id
Definition at line 40 of file remotetelescopedao.cpp.
References createObject(), db, and DatabaseConnectionSingleton::getDatabase().
Referenced by TelescopeDAO::get().
getAll()
QList< RemoteTelescope > RemoteTelescopeDAO::getAll ()
getAll Method for obtaining all Remote Telescopes in the database
Returns
QList<RemoteTelescope> List of all Remote Telescopes in the database
Definition at line 54 of file remotetelescopedao.cpp.
References createObject(), db, and DatabaseConnectionSingleton::getDatabase().
remove()
bool RemoteTelescopeDAO::remove (int id)
remove Method for removing Remote telescope by id
Parameters
id Id of the remote telescope to be removed
Returns
bool indicating if removing was successful
Definition at line 69 of file remotetelescopedao.cpp.
References db, and DatabaseConnectionSingleton::getDatabase().
save()
int RemoteTelescopeDAO::save (RemoteTelescope remoteTelescope)
save Method for saving an instance of RemoteTelescope
Parameters
remoteTelescope Remote Telescope to be saved
Returns
int id of the saved Remote telescope. -1 if error
Definition at line 3 of file remotetelescopedao.cpp.
References bindValues(), db, DatabaseConnectionSingleton::getDatabase(), and RemoteTelescope::id().
Referenced by TelescopeDAO::save().
update()
int RemoteTelescopeDAO::update (RemoteTelescope remoteTelescope)
update Method for updating a Remote Telescope
Parameters
remoteTelescope Remote Telescope to be updated
Returns
int id of the Remote Telescope. -1 if error
Definition at line 18 of file remotetelescopedao.cpp.
References bindValues(), db, DatabaseConnectionSingleton::getDatabase(), and RemoteTelescope::id().
Referenced by TelescopeView::connectionSettings(), and TelescopeDAO::update().
Member Data Documentation
db
DatabaseConnectionSingleton RemoteTelescopeDAO::db = DatabaseConnectionSingleton::instance() private
Definition at line 66 of file remotetelescopedao.h.
Referenced by get(), getAll(), remove(), save(), and update().
The documentation for this class was generated from the following files:
persistence/remotetelescopedao.h
persistence/remotetelescopedao.cpp