CollimatorDesktop: TelescopeView Class Reference
TelescopeView Class Reference
#include <telescopeview.h>
Signals
void propertiesChanged ()
Public Member Functions
TelescopeView (QWidget *parent=nullptr)
~TelescopeView ()
void setTelescope (TelescopeUI)
Private Slots
void changeProperties ()
void openImageFromFile ()
void openImageProcessing ()
void screwsSettings ()
void saveTelescope ()
void saveScreenshot ()
void connectionSettings ()
void connectTelescope ()
void disconnectTelescope ()
void connectedChanged (bool)
Private Member Functions
void setAutomatic (bool)
Private Attributes
Ui::TelescopeView * ui
CollimatorImage * image
TelescopeUI telescope
RemoteTelescope remoteTelescope
Detailed Description
Definition at line 18 of file telescopeview.h.
Constructor & Destructor Documentation
TelescopeView()
TelescopeView::TelescopeView (QWidget * parent = nullptr) explicit
Definition at line 20 of file telescopeview.cpp.
References changeProperties(), CollimatorImage::connectedChanged(), connectedChanged(), connectionSettings(), connectTelescope(), image, openImageFromFile(), openImageProcessing(), CollimatorImage::propertiesChanged(), propertiesChanged(), saveScreenshot(), screwsSettings(), CollimatorImage::setScrollArea(), CollimatorImage::setTelescope(), telescope, ui, and CollimatorImage::zoom().
~TelescopeView()
TelescopeView::~TelescopeView ()
Definition at line 65 of file telescopeview.cpp.
References ui.
Member Function Documentation
changeProperties
void TelescopeView::changeProperties () private slot
Definition at line 238 of file telescopeview.cpp.
References PaintingProperties::Mirroring::horizontally, image, TelescopeUI::paintingProperties(), propertiesChanged(), CollimatorImage::setDebug(), PaintingProperties::setImageMirroring(), PaintingProperties::setScrewsMirroring(), PaintingProperties::setTigthMirroring(), PaintingProperties::setViewBoundingBox(), PaintingProperties::setViewCalculatedCenter(), PaintingProperties::setViewScrews(), telescope, ui, and PaintingProperties::Mirroring::vertically.
Referenced by TelescopeView().
connectedChanged
void TelescopeView::connectedChanged (bool connected) private slot
Definition at line 219 of file telescopeview.cpp.
References connectTelescope(), disconnectTelescope(), and ui.
Referenced by TelescopeView().
connectionSettings
void TelescopeView::connectionSettings () private slot
Definition at line 184 of file telescopeview.cpp.
References RemoteTelescope::isValid(), Telescope::remoteTelescope(), ConnectionSettingsDialog::remoteTelescope(), remoteTelescope, ConnectionSettingsDialog::setRemoteTelescope(), telescope, ui, and RemoteTelescopeDAO::update().
Referenced by TelescopeView().
connectTelescope
void TelescopeView::connectTelescope () private slot
Definition at line 209 of file telescopeview.cpp.
References CollimatorImage::connectTelescope(), image, and remoteTelescope.
Referenced by connectedChanged(), and TelescopeView().
disconnectTelescope
void TelescopeView::disconnectTelescope () private slot
Definition at line 214 of file telescopeview.cpp.
References image, and CollimatorImage::setConnected().
Referenced by connectedChanged().
openImageFromFile
void TelescopeView::openImageFromFile () private slot
Definition at line 93 of file telescopeview.cpp.
References image, and CollimatorImage::loadImage().
Referenced by TelescopeView().
openImageProcessing
void TelescopeView::openImageProcessing () private slot
Definition at line 101 of file telescopeview.cpp.
References Telescope::processingProperties(), ProcessingPropertiesSettings::processingProperties(), propertiesChanged(), Telescope::setProcessingProperties(), ProcessingPropertiesSettings::setProcessingProperties(), telescope, and ProcessingPropertiesDAO::update().
Referenced by TelescopeView().
propertiesChanged
void TelescopeView::propertiesChanged () signal
Referenced by changeProperties(), openImageProcessing(), screwsSettings(), setAutomatic(), setTelescope(), and TelescopeView().
saveScreenshot
void TelescopeView::saveScreenshot () private slot
Definition at line 177 of file telescopeview.cpp.
References image.
Referenced by TelescopeView().
saveTelescope
void TelescopeView::saveTelescope () private slot
Definition at line 171 of file telescopeview.cpp.
References telescope, and TelescopeDAO::update().
Referenced by setTelescope().
screwsSettings
void TelescopeView::screwsSettings () private slot
Definition at line 129 of file telescopeview.cpp.
References TelescopeUI::paintingProperties(), propertiesChanged(), ScrewsDialog::radius(), Telescope::screws(), ScrewsDialog::screws(), PaintingProperties::screwsRadius(), ScrewsDialog::setRadius(), Telescope::setScrews(), ScrewsDialog::setScrews(), PaintingProperties::setScrewsRadius(), telescope, and TelescopeDAO::update().
Referenced by TelescopeView().
setAutomatic()
void TelescopeView::setAutomatic (bool automatic) private
Definition at line 156 of file telescopeview.cpp.
References TelescopeUI::paintingProperties(), propertiesChanged(), PaintingProperties::setAutomatic(), telescope, and ui.
Referenced by setTelescope().
setTelescope()
void TelescopeView::setTelescope (TelescopeUI telescope)
Definition at line 71 of file telescopeview.cpp.
References PaintingProperties::automatic(), PaintingProperties::Mirroring::horizontally, PaintingProperties::imageMirroring(), RemoteTelescope::isValid(), Telescope::name(), TelescopeUI::paintingProperties(), propertiesChanged(), Telescope::remoteTelescope(), remoteTelescope, saveTelescope(), PaintingProperties::screwsMirroring(), setAutomatic(), telescope, PaintingProperties::tightMirroring(), ui, PaintingProperties::Mirroring::vertically, PaintingProperties::viewBoundingBox(), PaintingProperties::viewCalculatedCenter(), and PaintingProperties::viewScrews().
Referenced by TelescopeSelector::onClickTelescope().
Member Data Documentation
image
CollimatorImage* TelescopeView::image private
Definition at line 29 of file telescopeview.h.
Referenced by changeProperties(), connectTelescope(), disconnectTelescope(), openImageFromFile(), saveScreenshot(), and TelescopeView().
remoteTelescope
RemoteTelescope TelescopeView::remoteTelescope private
Definition at line 31 of file telescopeview.h.
Referenced by connectionSettings(), connectTelescope(), and setTelescope().
telescope
TelescopeUI TelescopeView::telescope private
Definition at line 30 of file telescopeview.h.
Referenced by changeProperties(), connectionSettings(), openImageProcessing(), saveTelescope(), screwsSettings(), setAutomatic(), setTelescope(), and TelescopeView().
ui
Ui::TelescopeView* TelescopeView::ui private
Definition at line 28 of file telescopeview.h.
Referenced by changeProperties(), connectedChanged(), connectionSettings(), setAutomatic(), setTelescope(), TelescopeView(), and ~TelescopeView().
The documentation for this class was generated from the following files:
views/telescopeview.h
views/telescopeview.cpp