CollimatorDesktop: ProcessingPropertiesSettings Class Reference
ProcessingPropertiesSettings Class Reference
#include <processingpropertiessettings.h>
Public Member Functions
ProcessingPropertiesSettings (QWidget *parent=nullptr)
~ProcessingPropertiesSettings ()
void setProcessingProperties (ProcessingProperties processingProperties)
setProcessingProperties Sets the processing properties from where to show the data
ProcessingProperties processingProperties ()
processingProperties Returns the current ProcessingProperties with values from UI
Private Member Functions
void setValuesOnScreen (ProcessingProperties processingProperties)
Private Attributes
Ui::ProcessingPropertiesSettings * ui
ProcessingProperties m_processingProperties
Detailed Description
Definition at line 11 of file processingpropertiessettings.h.
Constructor & Destructor Documentation
ProcessingPropertiesSettings()
ProcessingPropertiesSettings::ProcessingPropertiesSettings (QWidget * parent = nullptr) explicit
Definition at line 5 of file processingpropertiessettings.cpp.
References ui.
~ProcessingPropertiesSettings()
ProcessingPropertiesSettings::~ProcessingPropertiesSettings ()
Definition at line 13 of file processingpropertiessettings.cpp.
References ui.
Member Function Documentation
processingProperties()
ProcessingProperties ProcessingPropertiesSettings::processingProperties ()
processingProperties Returns the current ProcessingProperties with values from UI
Returns
ProcessingProperties with values from UI
Definition at line 24 of file processingpropertiessettings.cpp.
References ProcessingProperties::ThresholdValues::constant, m_processingProperties, ProcessingProperties::StretchingValues::max, ProcessingProperties::StretchingValues::min, ProcessingProperties::setRefinateRadius(), ProcessingProperties::setStretchingValues(), ProcessingProperties::setThresholdValues(), ProcessingProperties::ThresholdValues::thresholdSize, and ui.
Referenced by TelescopeView::openImageProcessing(), setProcessingProperties(), and setValuesOnScreen().
setProcessingProperties()
void ProcessingPropertiesSettings::setProcessingProperties (ProcessingProperties processingProperties)
setProcessingProperties Sets the processing properties from where to show the data
Parameters
processingProperties Processing Properties with data
Definition at line 18 of file processingpropertiessettings.cpp.
References m_processingProperties, processingProperties(), and setValuesOnScreen().
Referenced by TelescopeView::openImageProcessing().
setValuesOnScreen()
void ProcessingPropertiesSettings::setValuesOnScreen (ProcessingProperties processingProperties) private
Definition at line 41 of file processingpropertiessettings.cpp.
References ProcessingProperties::ThresholdValues::constant, ProcessingProperties::StretchingValues::max, ProcessingProperties::StretchingValues::min, processingProperties(), ProcessingProperties::refinateRadius(), ProcessingProperties::stretchingValues(), ProcessingProperties::ThresholdValues::thresholdSize, ProcessingProperties::thresholdValues(), and ui.
Referenced by setProcessingProperties().
Member Data Documentation
m_processingProperties
ProcessingProperties ProcessingPropertiesSettings::m_processingProperties private
Definition at line 34 of file processingpropertiessettings.h.
Referenced by processingProperties(), and setProcessingProperties().
ui
Ui::ProcessingPropertiesSettings* ProcessingPropertiesSettings::ui private
Definition at line 33 of file processingpropertiessettings.h.
Referenced by processingProperties(), ProcessingPropertiesSettings(), setValuesOnScreen(), and ~ProcessingPropertiesSettings().
The documentation for this class was generated from the following files:
views/processingpropertiessettings.h
views/processingpropertiessettings.cpp