CollimatorDesktop: logic/collimatorimage.cpp File Reference
collimatorimage.cpp File Reference
#include "collimatorimage.h"
#include <collimator.h>
#include <imageresults.h>
#include <qpainter.h>
#include <qscrollbar.h>
#include <QtMath>
#include <QDebug>
#include <qpixmap.h>
#include <QTimer>
#include <model/indiclient.h>
Functions
float calculateScrewsDegrees (Screw screw, PaintingProperties paintingProperties)
Function Documentation
calculateScrewsDegrees()
float calculateScrewsDegrees (Screw screw, PaintingProperties paintingProperties)
Definition at line 82 of file collimatorimage.cpp.
References Screw::degrees(), PaintingProperties::Mirroring::horizontally, PaintingProperties::screwsMirroring(), and PaintingProperties::Mirroring::vertically.
Referenced by CollimatorImage::refreshImage().