CollimatorDesktop: CollimatorLib/model/screw.h File Reference
screw.h File Reference
#include "CollimatorLib_global.h"
#include <QPoint>
#include <QHash>
Classes
class Screw
Functions
bool operator== (const Screw &sc1, const Screw &sc2)
uint qHash (const Screw &key, uint seed)
Function Documentation
operator==()
bool operator== (const Screw & sc1, const Screw & sc2) inline
Definition at line 26 of file screw.h.
References Screw::id().
qHash()
uint qHash (const Screw & key, uint seed) inline
Definition at line 33 of file screw.h.
References Screw::degrees(), and Screw::id().